// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: serviceaccount/v1/serviceaccount.proto

package serviceaccountv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/sdk/proto/serviceaccount/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ServiceAccountAPIName is the fully-qualified name of the ServiceAccountAPI service.
	ServiceAccountAPIName = "admiral.api.serviceaccount.v1.ServiceAccountAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ServiceAccountAPICreateServiceAccountProcedure is the fully-qualified name of the
	// ServiceAccountAPI's CreateServiceAccount RPC.
	ServiceAccountAPICreateServiceAccountProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/CreateServiceAccount"
	// ServiceAccountAPIGetServiceAccountProcedure is the fully-qualified name of the
	// ServiceAccountAPI's GetServiceAccount RPC.
	ServiceAccountAPIGetServiceAccountProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/GetServiceAccount"
	// ServiceAccountAPIListServiceAccountsProcedure is the fully-qualified name of the
	// ServiceAccountAPI's ListServiceAccounts RPC.
	ServiceAccountAPIListServiceAccountsProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/ListServiceAccounts"
	// ServiceAccountAPIUpdateServiceAccountProcedure is the fully-qualified name of the
	// ServiceAccountAPI's UpdateServiceAccount RPC.
	ServiceAccountAPIUpdateServiceAccountProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/UpdateServiceAccount"
	// ServiceAccountAPIDeleteServiceAccountProcedure is the fully-qualified name of the
	// ServiceAccountAPI's DeleteServiceAccount RPC.
	ServiceAccountAPIDeleteServiceAccountProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/DeleteServiceAccount"
	// ServiceAccountAPICreateServiceAccountTokenProcedure is the fully-qualified name of the
	// ServiceAccountAPI's CreateServiceAccountToken RPC.
	ServiceAccountAPICreateServiceAccountTokenProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/CreateServiceAccountToken"
	// ServiceAccountAPIListServiceAccountTokensProcedure is the fully-qualified name of the
	// ServiceAccountAPI's ListServiceAccountTokens RPC.
	ServiceAccountAPIListServiceAccountTokensProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/ListServiceAccountTokens"
	// ServiceAccountAPIGetServiceAccountTokenProcedure is the fully-qualified name of the
	// ServiceAccountAPI's GetServiceAccountToken RPC.
	ServiceAccountAPIGetServiceAccountTokenProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/GetServiceAccountToken"
	// ServiceAccountAPIRevokeServiceAccountTokenProcedure is the fully-qualified name of the
	// ServiceAccountAPI's RevokeServiceAccountToken RPC.
	ServiceAccountAPIRevokeServiceAccountTokenProcedure = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/RevokeServiceAccountToken"
)

// ServiceAccountAPIClient is a client for the admiral.api.serviceaccount.v1.ServiceAccountAPI
// service.
type ServiceAccountAPIClient interface {
	// CreateServiceAccount creates a new service account within the caller's tenant.
	//
	// Scope: `sa:write`
	CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error)
	// GetServiceAccount retrieves a service account by ID.
	//
	// Scope: `sa:read`
	GetServiceAccount(context.Context, *connect.Request[v1.GetServiceAccountRequest]) (*connect.Response[v1.GetServiceAccountResponse], error)
	// ListServiceAccounts returns a paginated list of service accounts
	// within the caller's tenant.
	//
	// Scope: `sa:read`
	ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error)
	// UpdateServiceAccount updates a service account's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	// Setting status to DISABLED invalidates all associated SATs.
	//
	// Scope: `sa:write`
	UpdateServiceAccount(context.Context, *connect.Request[v1.UpdateServiceAccountRequest]) (*connect.Response[v1.UpdateServiceAccountResponse], error)
	// DeleteServiceAccount permanently deletes a service account and revokes
	// all associated SATs. This action cannot be undone.
	//
	// Scope: `sa:write`
	DeleteServiceAccount(context.Context, *connect.Request[v1.DeleteServiceAccountRequest]) (*connect.Response[v1.DeleteServiceAccountResponse], error)
	// CreateServiceAccountToken creates a new SAT under the specified service
	// account. The token's scopes must be a subset of the parent service
	// account's allowed scopes. The response includes the raw token secret,
	// which is shown exactly once.
	//
	// Scope: `sa:write`
	CreateServiceAccountToken(context.Context, *connect.Request[v1.CreateServiceAccountTokenRequest]) (*connect.Response[v1.CreateServiceAccountTokenResponse], error)
	// ListServiceAccountTokens returns a paginated list of tokens for a
	// service account. Token secrets are never included.
	//
	// Scope: `sa:read`
	ListServiceAccountTokens(context.Context, *connect.Request[v1.ListServiceAccountTokensRequest]) (*connect.Response[v1.ListServiceAccountTokensResponse], error)
	// GetServiceAccountToken retrieves a single SAT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `sa:read`
	GetServiceAccountToken(context.Context, *connect.Request[v1.GetServiceAccountTokenRequest]) (*connect.Response[v1.GetServiceAccountTokenResponse], error)
	// RevokeServiceAccountToken permanently revokes a SAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `sa:write`
	RevokeServiceAccountToken(context.Context, *connect.Request[v1.RevokeServiceAccountTokenRequest]) (*connect.Response[v1.RevokeServiceAccountTokenResponse], error)
}

// NewServiceAccountAPIClient constructs a client for the
// admiral.api.serviceaccount.v1.ServiceAccountAPI service. By default, it uses the Connect protocol
// with the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To
// use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb()
// options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewServiceAccountAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ServiceAccountAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	serviceAccountAPIMethods := v1.File_serviceaccount_v1_serviceaccount_proto.Services().ByName("ServiceAccountAPI").Methods()
	return &serviceAccountAPIClient{
		createServiceAccount: connect.NewClient[v1.CreateServiceAccountRequest, v1.CreateServiceAccountResponse](
			httpClient,
			baseURL+ServiceAccountAPICreateServiceAccountProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("CreateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		getServiceAccount: connect.NewClient[v1.GetServiceAccountRequest, v1.GetServiceAccountResponse](
			httpClient,
			baseURL+ServiceAccountAPIGetServiceAccountProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("GetServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccounts: connect.NewClient[v1.ListServiceAccountsRequest, v1.ListServiceAccountsResponse](
			httpClient,
			baseURL+ServiceAccountAPIListServiceAccountsProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("ListServiceAccounts")),
			connect.WithClientOptions(opts...),
		),
		updateServiceAccount: connect.NewClient[v1.UpdateServiceAccountRequest, v1.UpdateServiceAccountResponse](
			httpClient,
			baseURL+ServiceAccountAPIUpdateServiceAccountProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("UpdateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		deleteServiceAccount: connect.NewClient[v1.DeleteServiceAccountRequest, v1.DeleteServiceAccountResponse](
			httpClient,
			baseURL+ServiceAccountAPIDeleteServiceAccountProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("DeleteServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccountToken: connect.NewClient[v1.CreateServiceAccountTokenRequest, v1.CreateServiceAccountTokenResponse](
			httpClient,
			baseURL+ServiceAccountAPICreateServiceAccountTokenProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("CreateServiceAccountToken")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccountTokens: connect.NewClient[v1.ListServiceAccountTokensRequest, v1.ListServiceAccountTokensResponse](
			httpClient,
			baseURL+ServiceAccountAPIListServiceAccountTokensProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("ListServiceAccountTokens")),
			connect.WithClientOptions(opts...),
		),
		getServiceAccountToken: connect.NewClient[v1.GetServiceAccountTokenRequest, v1.GetServiceAccountTokenResponse](
			httpClient,
			baseURL+ServiceAccountAPIGetServiceAccountTokenProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("GetServiceAccountToken")),
			connect.WithClientOptions(opts...),
		),
		revokeServiceAccountToken: connect.NewClient[v1.RevokeServiceAccountTokenRequest, v1.RevokeServiceAccountTokenResponse](
			httpClient,
			baseURL+ServiceAccountAPIRevokeServiceAccountTokenProcedure,
			connect.WithSchema(serviceAccountAPIMethods.ByName("RevokeServiceAccountToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// serviceAccountAPIClient implements ServiceAccountAPIClient.
type serviceAccountAPIClient struct {
	createServiceAccount      *connect.Client[v1.CreateServiceAccountRequest, v1.CreateServiceAccountResponse]
	getServiceAccount         *connect.Client[v1.GetServiceAccountRequest, v1.GetServiceAccountResponse]
	listServiceAccounts       *connect.Client[v1.ListServiceAccountsRequest, v1.ListServiceAccountsResponse]
	updateServiceAccount      *connect.Client[v1.UpdateServiceAccountRequest, v1.UpdateServiceAccountResponse]
	deleteServiceAccount      *connect.Client[v1.DeleteServiceAccountRequest, v1.DeleteServiceAccountResponse]
	createServiceAccountToken *connect.Client[v1.CreateServiceAccountTokenRequest, v1.CreateServiceAccountTokenResponse]
	listServiceAccountTokens  *connect.Client[v1.ListServiceAccountTokensRequest, v1.ListServiceAccountTokensResponse]
	getServiceAccountToken    *connect.Client[v1.GetServiceAccountTokenRequest, v1.GetServiceAccountTokenResponse]
	revokeServiceAccountToken *connect.Client[v1.RevokeServiceAccountTokenRequest, v1.RevokeServiceAccountTokenResponse]
}

// CreateServiceAccount calls admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccount.
func (c *serviceAccountAPIClient) CreateServiceAccount(ctx context.Context, req *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error) {
	return c.createServiceAccount.CallUnary(ctx, req)
}

// GetServiceAccount calls admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccount.
func (c *serviceAccountAPIClient) GetServiceAccount(ctx context.Context, req *connect.Request[v1.GetServiceAccountRequest]) (*connect.Response[v1.GetServiceAccountResponse], error) {
	return c.getServiceAccount.CallUnary(ctx, req)
}

// ListServiceAccounts calls admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccounts.
func (c *serviceAccountAPIClient) ListServiceAccounts(ctx context.Context, req *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error) {
	return c.listServiceAccounts.CallUnary(ctx, req)
}

// UpdateServiceAccount calls admiral.api.serviceaccount.v1.ServiceAccountAPI.UpdateServiceAccount.
func (c *serviceAccountAPIClient) UpdateServiceAccount(ctx context.Context, req *connect.Request[v1.UpdateServiceAccountRequest]) (*connect.Response[v1.UpdateServiceAccountResponse], error) {
	return c.updateServiceAccount.CallUnary(ctx, req)
}

// DeleteServiceAccount calls admiral.api.serviceaccount.v1.ServiceAccountAPI.DeleteServiceAccount.
func (c *serviceAccountAPIClient) DeleteServiceAccount(ctx context.Context, req *connect.Request[v1.DeleteServiceAccountRequest]) (*connect.Response[v1.DeleteServiceAccountResponse], error) {
	return c.deleteServiceAccount.CallUnary(ctx, req)
}

// CreateServiceAccountToken calls
// admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccountToken.
func (c *serviceAccountAPIClient) CreateServiceAccountToken(ctx context.Context, req *connect.Request[v1.CreateServiceAccountTokenRequest]) (*connect.Response[v1.CreateServiceAccountTokenResponse], error) {
	return c.createServiceAccountToken.CallUnary(ctx, req)
}

// ListServiceAccountTokens calls
// admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccountTokens.
func (c *serviceAccountAPIClient) ListServiceAccountTokens(ctx context.Context, req *connect.Request[v1.ListServiceAccountTokensRequest]) (*connect.Response[v1.ListServiceAccountTokensResponse], error) {
	return c.listServiceAccountTokens.CallUnary(ctx, req)
}

// GetServiceAccountToken calls
// admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccountToken.
func (c *serviceAccountAPIClient) GetServiceAccountToken(ctx context.Context, req *connect.Request[v1.GetServiceAccountTokenRequest]) (*connect.Response[v1.GetServiceAccountTokenResponse], error) {
	return c.getServiceAccountToken.CallUnary(ctx, req)
}

// RevokeServiceAccountToken calls
// admiral.api.serviceaccount.v1.ServiceAccountAPI.RevokeServiceAccountToken.
func (c *serviceAccountAPIClient) RevokeServiceAccountToken(ctx context.Context, req *connect.Request[v1.RevokeServiceAccountTokenRequest]) (*connect.Response[v1.RevokeServiceAccountTokenResponse], error) {
	return c.revokeServiceAccountToken.CallUnary(ctx, req)
}

// ServiceAccountAPIHandler is an implementation of the
// admiral.api.serviceaccount.v1.ServiceAccountAPI service.
type ServiceAccountAPIHandler interface {
	// CreateServiceAccount creates a new service account within the caller's tenant.
	//
	// Scope: `sa:write`
	CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error)
	// GetServiceAccount retrieves a service account by ID.
	//
	// Scope: `sa:read`
	GetServiceAccount(context.Context, *connect.Request[v1.GetServiceAccountRequest]) (*connect.Response[v1.GetServiceAccountResponse], error)
	// ListServiceAccounts returns a paginated list of service accounts
	// within the caller's tenant.
	//
	// Scope: `sa:read`
	ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error)
	// UpdateServiceAccount updates a service account's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	// Setting status to DISABLED invalidates all associated SATs.
	//
	// Scope: `sa:write`
	UpdateServiceAccount(context.Context, *connect.Request[v1.UpdateServiceAccountRequest]) (*connect.Response[v1.UpdateServiceAccountResponse], error)
	// DeleteServiceAccount permanently deletes a service account and revokes
	// all associated SATs. This action cannot be undone.
	//
	// Scope: `sa:write`
	DeleteServiceAccount(context.Context, *connect.Request[v1.DeleteServiceAccountRequest]) (*connect.Response[v1.DeleteServiceAccountResponse], error)
	// CreateServiceAccountToken creates a new SAT under the specified service
	// account. The token's scopes must be a subset of the parent service
	// account's allowed scopes. The response includes the raw token secret,
	// which is shown exactly once.
	//
	// Scope: `sa:write`
	CreateServiceAccountToken(context.Context, *connect.Request[v1.CreateServiceAccountTokenRequest]) (*connect.Response[v1.CreateServiceAccountTokenResponse], error)
	// ListServiceAccountTokens returns a paginated list of tokens for a
	// service account. Token secrets are never included.
	//
	// Scope: `sa:read`
	ListServiceAccountTokens(context.Context, *connect.Request[v1.ListServiceAccountTokensRequest]) (*connect.Response[v1.ListServiceAccountTokensResponse], error)
	// GetServiceAccountToken retrieves a single SAT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `sa:read`
	GetServiceAccountToken(context.Context, *connect.Request[v1.GetServiceAccountTokenRequest]) (*connect.Response[v1.GetServiceAccountTokenResponse], error)
	// RevokeServiceAccountToken permanently revokes a SAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `sa:write`
	RevokeServiceAccountToken(context.Context, *connect.Request[v1.RevokeServiceAccountTokenRequest]) (*connect.Response[v1.RevokeServiceAccountTokenResponse], error)
}

// NewServiceAccountAPIHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewServiceAccountAPIHandler(svc ServiceAccountAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	serviceAccountAPIMethods := v1.File_serviceaccount_v1_serviceaccount_proto.Services().ByName("ServiceAccountAPI").Methods()
	serviceAccountAPICreateServiceAccountHandler := connect.NewUnaryHandler(
		ServiceAccountAPICreateServiceAccountProcedure,
		svc.CreateServiceAccount,
		connect.WithSchema(serviceAccountAPIMethods.ByName("CreateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIGetServiceAccountHandler := connect.NewUnaryHandler(
		ServiceAccountAPIGetServiceAccountProcedure,
		svc.GetServiceAccount,
		connect.WithSchema(serviceAccountAPIMethods.ByName("GetServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIListServiceAccountsHandler := connect.NewUnaryHandler(
		ServiceAccountAPIListServiceAccountsProcedure,
		svc.ListServiceAccounts,
		connect.WithSchema(serviceAccountAPIMethods.ByName("ListServiceAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIUpdateServiceAccountHandler := connect.NewUnaryHandler(
		ServiceAccountAPIUpdateServiceAccountProcedure,
		svc.UpdateServiceAccount,
		connect.WithSchema(serviceAccountAPIMethods.ByName("UpdateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIDeleteServiceAccountHandler := connect.NewUnaryHandler(
		ServiceAccountAPIDeleteServiceAccountProcedure,
		svc.DeleteServiceAccount,
		connect.WithSchema(serviceAccountAPIMethods.ByName("DeleteServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPICreateServiceAccountTokenHandler := connect.NewUnaryHandler(
		ServiceAccountAPICreateServiceAccountTokenProcedure,
		svc.CreateServiceAccountToken,
		connect.WithSchema(serviceAccountAPIMethods.ByName("CreateServiceAccountToken")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIListServiceAccountTokensHandler := connect.NewUnaryHandler(
		ServiceAccountAPIListServiceAccountTokensProcedure,
		svc.ListServiceAccountTokens,
		connect.WithSchema(serviceAccountAPIMethods.ByName("ListServiceAccountTokens")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIGetServiceAccountTokenHandler := connect.NewUnaryHandler(
		ServiceAccountAPIGetServiceAccountTokenProcedure,
		svc.GetServiceAccountToken,
		connect.WithSchema(serviceAccountAPIMethods.ByName("GetServiceAccountToken")),
		connect.WithHandlerOptions(opts...),
	)
	serviceAccountAPIRevokeServiceAccountTokenHandler := connect.NewUnaryHandler(
		ServiceAccountAPIRevokeServiceAccountTokenProcedure,
		svc.RevokeServiceAccountToken,
		connect.WithSchema(serviceAccountAPIMethods.ByName("RevokeServiceAccountToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.api.serviceaccount.v1.ServiceAccountAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ServiceAccountAPICreateServiceAccountProcedure:
			serviceAccountAPICreateServiceAccountHandler.ServeHTTP(w, r)
		case ServiceAccountAPIGetServiceAccountProcedure:
			serviceAccountAPIGetServiceAccountHandler.ServeHTTP(w, r)
		case ServiceAccountAPIListServiceAccountsProcedure:
			serviceAccountAPIListServiceAccountsHandler.ServeHTTP(w, r)
		case ServiceAccountAPIUpdateServiceAccountProcedure:
			serviceAccountAPIUpdateServiceAccountHandler.ServeHTTP(w, r)
		case ServiceAccountAPIDeleteServiceAccountProcedure:
			serviceAccountAPIDeleteServiceAccountHandler.ServeHTTP(w, r)
		case ServiceAccountAPICreateServiceAccountTokenProcedure:
			serviceAccountAPICreateServiceAccountTokenHandler.ServeHTTP(w, r)
		case ServiceAccountAPIListServiceAccountTokensProcedure:
			serviceAccountAPIListServiceAccountTokensHandler.ServeHTTP(w, r)
		case ServiceAccountAPIGetServiceAccountTokenProcedure:
			serviceAccountAPIGetServiceAccountTokenHandler.ServeHTTP(w, r)
		case ServiceAccountAPIRevokeServiceAccountTokenProcedure:
			serviceAccountAPIRevokeServiceAccountTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedServiceAccountAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedServiceAccountAPIHandler struct{}

func (UnimplementedServiceAccountAPIHandler) CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccount is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) GetServiceAccount(context.Context, *connect.Request[v1.GetServiceAccountRequest]) (*connect.Response[v1.GetServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccount is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccounts is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) UpdateServiceAccount(context.Context, *connect.Request[v1.UpdateServiceAccountRequest]) (*connect.Response[v1.UpdateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.UpdateServiceAccount is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) DeleteServiceAccount(context.Context, *connect.Request[v1.DeleteServiceAccountRequest]) (*connect.Response[v1.DeleteServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.DeleteServiceAccount is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) CreateServiceAccountToken(context.Context, *connect.Request[v1.CreateServiceAccountTokenRequest]) (*connect.Response[v1.CreateServiceAccountTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccountToken is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) ListServiceAccountTokens(context.Context, *connect.Request[v1.ListServiceAccountTokensRequest]) (*connect.Response[v1.ListServiceAccountTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccountTokens is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) GetServiceAccountToken(context.Context, *connect.Request[v1.GetServiceAccountTokenRequest]) (*connect.Response[v1.GetServiceAccountTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccountToken is not implemented"))
}

func (UnimplementedServiceAccountAPIHandler) RevokeServiceAccountToken(context.Context, *connect.Request[v1.RevokeServiceAccountTokenRequest]) (*connect.Response[v1.RevokeServiceAccountTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.serviceaccount.v1.ServiceAccountAPI.RevokeServiceAccountToken is not implemented"))
}
