// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: serviceaccount/v1/serviceaccount.proto

package serviceaccountv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ServiceAccountAPI_CreateServiceAccount_FullMethodName      = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/CreateServiceAccount"
	ServiceAccountAPI_GetServiceAccount_FullMethodName         = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/GetServiceAccount"
	ServiceAccountAPI_ListServiceAccounts_FullMethodName       = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/ListServiceAccounts"
	ServiceAccountAPI_UpdateServiceAccount_FullMethodName      = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/UpdateServiceAccount"
	ServiceAccountAPI_DeleteServiceAccount_FullMethodName      = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/DeleteServiceAccount"
	ServiceAccountAPI_CreateServiceAccountToken_FullMethodName = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/CreateServiceAccountToken"
	ServiceAccountAPI_ListServiceAccountTokens_FullMethodName  = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/ListServiceAccountTokens"
	ServiceAccountAPI_GetServiceAccountToken_FullMethodName    = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/GetServiceAccountToken"
	ServiceAccountAPI_RevokeServiceAccountToken_FullMethodName = "/admiral.api.serviceaccount.v1.ServiceAccountAPI/RevokeServiceAccountToken"
)

// ServiceAccountAPIClient is the client API for ServiceAccountAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ServiceAccountAPI manages service accounts — first-class non-human identities
// within a tenant. Service accounts follow the Google Cloud IAM model: the
// account IS the identity, and Service Account Tokens (SATs) are credentials
// attached to it.
//
// A service account can have multiple SATs for zero-downtime key rotation.
// Deleting a service account automatically revokes all associated SATs.
// Disabling a service account invalidates all SATs without deleting them.
type ServiceAccountAPIClient interface {
	// CreateServiceAccount creates a new service account within the caller's tenant.
	//
	// Scope: `sa:write`
	CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest, opts ...grpc.CallOption) (*CreateServiceAccountResponse, error)
	// GetServiceAccount retrieves a service account by ID.
	//
	// Scope: `sa:read`
	GetServiceAccount(ctx context.Context, in *GetServiceAccountRequest, opts ...grpc.CallOption) (*GetServiceAccountResponse, error)
	// ListServiceAccounts returns a paginated list of service accounts
	// within the caller's tenant.
	//
	// Scope: `sa:read`
	ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest, opts ...grpc.CallOption) (*ListServiceAccountsResponse, error)
	// UpdateServiceAccount updates a service account's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	// Setting status to DISABLED invalidates all associated SATs.
	//
	// Scope: `sa:write`
	UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest, opts ...grpc.CallOption) (*UpdateServiceAccountResponse, error)
	// DeleteServiceAccount permanently deletes a service account and revokes
	// all associated SATs. This action cannot be undone.
	//
	// Scope: `sa:write`
	DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest, opts ...grpc.CallOption) (*DeleteServiceAccountResponse, error)
	// CreateServiceAccountToken creates a new SAT under the specified service
	// account. The token's scopes must be a subset of the parent service
	// account's allowed scopes. The response includes the raw token secret,
	// which is shown exactly once.
	//
	// Scope: `sa:write`
	CreateServiceAccountToken(ctx context.Context, in *CreateServiceAccountTokenRequest, opts ...grpc.CallOption) (*CreateServiceAccountTokenResponse, error)
	// ListServiceAccountTokens returns a paginated list of tokens for a
	// service account. Token secrets are never included.
	//
	// Scope: `sa:read`
	ListServiceAccountTokens(ctx context.Context, in *ListServiceAccountTokensRequest, opts ...grpc.CallOption) (*ListServiceAccountTokensResponse, error)
	// GetServiceAccountToken retrieves a single SAT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `sa:read`
	GetServiceAccountToken(ctx context.Context, in *GetServiceAccountTokenRequest, opts ...grpc.CallOption) (*GetServiceAccountTokenResponse, error)
	// RevokeServiceAccountToken permanently revokes a SAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `sa:write`
	RevokeServiceAccountToken(ctx context.Context, in *RevokeServiceAccountTokenRequest, opts ...grpc.CallOption) (*RevokeServiceAccountTokenResponse, error)
}

type serviceAccountAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewServiceAccountAPIClient(cc grpc.ClientConnInterface) ServiceAccountAPIClient {
	return &serviceAccountAPIClient{cc}
}

func (c *serviceAccountAPIClient) CreateServiceAccount(ctx context.Context, in *CreateServiceAccountRequest, opts ...grpc.CallOption) (*CreateServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_CreateServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) GetServiceAccount(ctx context.Context, in *GetServiceAccountRequest, opts ...grpc.CallOption) (*GetServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_GetServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) ListServiceAccounts(ctx context.Context, in *ListServiceAccountsRequest, opts ...grpc.CallOption) (*ListServiceAccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceAccountsResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_ListServiceAccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) UpdateServiceAccount(ctx context.Context, in *UpdateServiceAccountRequest, opts ...grpc.CallOption) (*UpdateServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_UpdateServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) DeleteServiceAccount(ctx context.Context, in *DeleteServiceAccountRequest, opts ...grpc.CallOption) (*DeleteServiceAccountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteServiceAccountResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_DeleteServiceAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) CreateServiceAccountToken(ctx context.Context, in *CreateServiceAccountTokenRequest, opts ...grpc.CallOption) (*CreateServiceAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateServiceAccountTokenResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_CreateServiceAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) ListServiceAccountTokens(ctx context.Context, in *ListServiceAccountTokensRequest, opts ...grpc.CallOption) (*ListServiceAccountTokensResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceAccountTokensResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_ListServiceAccountTokens_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) GetServiceAccountToken(ctx context.Context, in *GetServiceAccountTokenRequest, opts ...grpc.CallOption) (*GetServiceAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceAccountTokenResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_GetServiceAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceAccountAPIClient) RevokeServiceAccountToken(ctx context.Context, in *RevokeServiceAccountTokenRequest, opts ...grpc.CallOption) (*RevokeServiceAccountTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeServiceAccountTokenResponse)
	err := c.cc.Invoke(ctx, ServiceAccountAPI_RevokeServiceAccountToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServiceAccountAPIServer is the server API for ServiceAccountAPI service.
// All implementations should embed UnimplementedServiceAccountAPIServer
// for forward compatibility.
//
// ServiceAccountAPI manages service accounts — first-class non-human identities
// within a tenant. Service accounts follow the Google Cloud IAM model: the
// account IS the identity, and Service Account Tokens (SATs) are credentials
// attached to it.
//
// A service account can have multiple SATs for zero-downtime key rotation.
// Deleting a service account automatically revokes all associated SATs.
// Disabling a service account invalidates all SATs without deleting them.
type ServiceAccountAPIServer interface {
	// CreateServiceAccount creates a new service account within the caller's tenant.
	//
	// Scope: `sa:write`
	CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error)
	// GetServiceAccount retrieves a service account by ID.
	//
	// Scope: `sa:read`
	GetServiceAccount(context.Context, *GetServiceAccountRequest) (*GetServiceAccountResponse, error)
	// ListServiceAccounts returns a paginated list of service accounts
	// within the caller's tenant.
	//
	// Scope: `sa:read`
	ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error)
	// UpdateServiceAccount updates a service account's mutable fields.
	// Use the `update_mask` to specify which fields to update.
	// Setting status to DISABLED invalidates all associated SATs.
	//
	// Scope: `sa:write`
	UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error)
	// DeleteServiceAccount permanently deletes a service account and revokes
	// all associated SATs. This action cannot be undone.
	//
	// Scope: `sa:write`
	DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error)
	// CreateServiceAccountToken creates a new SAT under the specified service
	// account. The token's scopes must be a subset of the parent service
	// account's allowed scopes. The response includes the raw token secret,
	// which is shown exactly once.
	//
	// Scope: `sa:write`
	CreateServiceAccountToken(context.Context, *CreateServiceAccountTokenRequest) (*CreateServiceAccountTokenResponse, error)
	// ListServiceAccountTokens returns a paginated list of tokens for a
	// service account. Token secrets are never included.
	//
	// Scope: `sa:read`
	ListServiceAccountTokens(context.Context, *ListServiceAccountTokensRequest) (*ListServiceAccountTokensResponse, error)
	// GetServiceAccountToken retrieves a single SAT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `sa:read`
	GetServiceAccountToken(context.Context, *GetServiceAccountTokenRequest) (*GetServiceAccountTokenResponse, error)
	// RevokeServiceAccountToken permanently revokes a SAT. The token becomes
	// immediately unusable and cannot be restored.
	//
	// Scope: `sa:write`
	RevokeServiceAccountToken(context.Context, *RevokeServiceAccountTokenRequest) (*RevokeServiceAccountTokenResponse, error)
}

// UnimplementedServiceAccountAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedServiceAccountAPIServer struct{}

func (UnimplementedServiceAccountAPIServer) CreateServiceAccount(context.Context, *CreateServiceAccountRequest) (*CreateServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceAccount not implemented")
}
func (UnimplementedServiceAccountAPIServer) GetServiceAccount(context.Context, *GetServiceAccountRequest) (*GetServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceAccount not implemented")
}
func (UnimplementedServiceAccountAPIServer) ListServiceAccounts(context.Context, *ListServiceAccountsRequest) (*ListServiceAccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceAccounts not implemented")
}
func (UnimplementedServiceAccountAPIServer) UpdateServiceAccount(context.Context, *UpdateServiceAccountRequest) (*UpdateServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateServiceAccount not implemented")
}
func (UnimplementedServiceAccountAPIServer) DeleteServiceAccount(context.Context, *DeleteServiceAccountRequest) (*DeleteServiceAccountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteServiceAccount not implemented")
}
func (UnimplementedServiceAccountAPIServer) CreateServiceAccountToken(context.Context, *CreateServiceAccountTokenRequest) (*CreateServiceAccountTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateServiceAccountToken not implemented")
}
func (UnimplementedServiceAccountAPIServer) ListServiceAccountTokens(context.Context, *ListServiceAccountTokensRequest) (*ListServiceAccountTokensResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServiceAccountTokens not implemented")
}
func (UnimplementedServiceAccountAPIServer) GetServiceAccountToken(context.Context, *GetServiceAccountTokenRequest) (*GetServiceAccountTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceAccountToken not implemented")
}
func (UnimplementedServiceAccountAPIServer) RevokeServiceAccountToken(context.Context, *RevokeServiceAccountTokenRequest) (*RevokeServiceAccountTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeServiceAccountToken not implemented")
}
func (UnimplementedServiceAccountAPIServer) testEmbeddedByValue() {}

// UnsafeServiceAccountAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServiceAccountAPIServer will
// result in compilation errors.
type UnsafeServiceAccountAPIServer interface {
	mustEmbedUnimplementedServiceAccountAPIServer()
}

func RegisterServiceAccountAPIServer(s grpc.ServiceRegistrar, srv ServiceAccountAPIServer) {
	// If the following call panics, it indicates UnimplementedServiceAccountAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ServiceAccountAPI_ServiceDesc, srv)
}

func _ServiceAccountAPI_CreateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).CreateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_CreateServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).CreateServiceAccount(ctx, req.(*CreateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_GetServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).GetServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_GetServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).GetServiceAccount(ctx, req.(*GetServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_ListServiceAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).ListServiceAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_ListServiceAccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).ListServiceAccounts(ctx, req.(*ListServiceAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_UpdateServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).UpdateServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_UpdateServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).UpdateServiceAccount(ctx, req.(*UpdateServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_DeleteServiceAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteServiceAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).DeleteServiceAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_DeleteServiceAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).DeleteServiceAccount(ctx, req.(*DeleteServiceAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_CreateServiceAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).CreateServiceAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_CreateServiceAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).CreateServiceAccountToken(ctx, req.(*CreateServiceAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_ListServiceAccountTokens_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServiceAccountTokensRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).ListServiceAccountTokens(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_ListServiceAccountTokens_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).ListServiceAccountTokens(ctx, req.(*ListServiceAccountTokensRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_GetServiceAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).GetServiceAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_GetServiceAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).GetServiceAccountToken(ctx, req.(*GetServiceAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ServiceAccountAPI_RevokeServiceAccountToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeServiceAccountTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceAccountAPIServer).RevokeServiceAccountToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ServiceAccountAPI_RevokeServiceAccountToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceAccountAPIServer).RevokeServiceAccountToken(ctx, req.(*RevokeServiceAccountTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ServiceAccountAPI_ServiceDesc is the grpc.ServiceDesc for ServiceAccountAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ServiceAccountAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.api.serviceaccount.v1.ServiceAccountAPI",
	HandlerType: (*ServiceAccountAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateServiceAccount",
			Handler:    _ServiceAccountAPI_CreateServiceAccount_Handler,
		},
		{
			MethodName: "GetServiceAccount",
			Handler:    _ServiceAccountAPI_GetServiceAccount_Handler,
		},
		{
			MethodName: "ListServiceAccounts",
			Handler:    _ServiceAccountAPI_ListServiceAccounts_Handler,
		},
		{
			MethodName: "UpdateServiceAccount",
			Handler:    _ServiceAccountAPI_UpdateServiceAccount_Handler,
		},
		{
			MethodName: "DeleteServiceAccount",
			Handler:    _ServiceAccountAPI_DeleteServiceAccount_Handler,
		},
		{
			MethodName: "CreateServiceAccountToken",
			Handler:    _ServiceAccountAPI_CreateServiceAccountToken_Handler,
		},
		{
			MethodName: "ListServiceAccountTokens",
			Handler:    _ServiceAccountAPI_ListServiceAccountTokens_Handler,
		},
		{
			MethodName: "GetServiceAccountToken",
			Handler:    _ServiceAccountAPI_GetServiceAccountToken_Handler,
		},
		{
			MethodName: "RevokeServiceAccountToken",
			Handler:    _ServiceAccountAPI_RevokeServiceAccountToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "serviceaccount/v1/serviceaccount.proto",
}
