// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: serviceaccount/v1/serviceaccount.proto

package serviceaccountv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "go.admiral.io/sdk/proto/accesstoken/v1"
	_ "go.admiral.io/sdk/proto/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ServiceAccountStatus represents the lifecycle state of a service account.
type ServiceAccountStatus int32

const (
	// Default value. Must not be used.
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_UNSPECIFIED ServiceAccountStatus = 0
	// The service account is active and its SATs can be used for authentication.
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_ACTIVE ServiceAccountStatus = 1
	// The service account is disabled. All associated SATs are invalidated
	// and cannot be used until the account is re-enabled.
	ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_DISABLED ServiceAccountStatus = 2
)

// Enum value maps for ServiceAccountStatus.
var (
	ServiceAccountStatus_name = map[int32]string{
		0: "SERVICE_ACCOUNT_STATUS_UNSPECIFIED",
		1: "SERVICE_ACCOUNT_STATUS_ACTIVE",
		2: "SERVICE_ACCOUNT_STATUS_DISABLED",
	}
	ServiceAccountStatus_value = map[string]int32{
		"SERVICE_ACCOUNT_STATUS_UNSPECIFIED": 0,
		"SERVICE_ACCOUNT_STATUS_ACTIVE":      1,
		"SERVICE_ACCOUNT_STATUS_DISABLED":    2,
	}
)

func (x ServiceAccountStatus) Enum() *ServiceAccountStatus {
	p := new(ServiceAccountStatus)
	*p = x
	return p
}

func (x ServiceAccountStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceAccountStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_serviceaccount_v1_serviceaccount_proto_enumTypes[0].Descriptor()
}

func (ServiceAccountStatus) Type() protoreflect.EnumType {
	return &file_serviceaccount_v1_serviceaccount_proto_enumTypes[0]
}

func (x ServiceAccountStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceAccountStatus.Descriptor instead.
func (ServiceAccountStatus) EnumDescriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{0}
}

// ServiceAccount is a first-class non-human identity within a tenant.
// It represents a machine identity (e.g., CI/CD pipeline, external integration)
// and can have multiple SATs (credentials) attached for key rotation.
type ServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the service account (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant this service account belongs to (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Human-readable name, unique within the tenant (e.g., "ci-pipeline").
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional description of the service account's purpose
	// (e.g., "GitHub Actions deployment automation").
	Description string `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	// The set of scopes this service account is allowed to use.
	// SATs created under this account can only request a subset of these scopes.
	Scopes []string `protobuf:"bytes,5,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Current lifecycle status.
	Status ServiceAccountStatus `protobuf:"varint,6,opt,name=status,proto3,enum=admiral.api.serviceaccount.v1.ServiceAccountStatus" json:"status,omitempty"`
	// The user who created this service account (UUID). For audit purposes only —
	// the service account is not bound to this user's access.
	CreatedBy string `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// When the service account was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the service account was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceAccount) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ServiceAccount) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ServiceAccount) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ServiceAccount) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceAccount) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ServiceAccount) GetStatus() ServiceAccountStatus {
	if x != nil {
		return x.Status
	}
	return ServiceAccountStatus_SERVICE_ACCOUNT_STATUS_UNSPECIFIED
}

func (x *ServiceAccount) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *ServiceAccount) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ServiceAccount) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// CreateServiceAccountRequest contains the parameters for creating a new service account.
type CreateServiceAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the service account (e.g., "ci-pipeline").
	// Must be unique within the tenant.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Optional description of the service account's purpose.
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// The scopes this service account is allowed to use. SATs created under
	// this account can only request a subset of these scopes.
	Scopes        []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountRequest) Reset() {
	*x = CreateServiceAccountRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountRequest) ProtoMessage() {}

func (x *CreateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{1}
}

func (x *CreateServiceAccountRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateServiceAccountRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// CreateServiceAccountResponse contains the newly created service account.
type CreateServiceAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created service account.
	ServiceAccount *ServiceAccount `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServiceAccountResponse) Reset() {
	*x = CreateServiceAccountResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountResponse) ProtoMessage() {}

func (x *CreateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{2}
}

func (x *CreateServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

// GetServiceAccountRequest identifies a service account to retrieve.
type GetServiceAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the service account (UUID).
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetServiceAccountRequest) Reset() {
	*x = GetServiceAccountRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountRequest) ProtoMessage() {}

func (x *GetServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*GetServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{3}
}

func (x *GetServiceAccountRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

// GetServiceAccountResponse contains the requested service account.
type GetServiceAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account.
	ServiceAccount *ServiceAccount `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetServiceAccountResponse) Reset() {
	*x = GetServiceAccountResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountResponse) ProtoMessage() {}

func (x *GetServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*GetServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{4}
}

func (x *GetServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

// ListServiceAccountsRequest contains pagination and filter parameters.
type ListServiceAccountsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of service accounts to return per page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque pagination token from a previous response.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter expression using the PEG filter DSL
	// (e.g., `status = "active"` or `display_name = "ci-*"`).
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountsRequest) Reset() {
	*x = ListServiceAccountsRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsRequest) ProtoMessage() {}

func (x *ListServiceAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{5}
}

func (x *ListServiceAccountsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServiceAccountsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListServiceAccountsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ListServiceAccountsResponse contains a page of service accounts.
type ListServiceAccountsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of service accounts.
	ServiceAccounts []*ServiceAccount `protobuf:"bytes,1,rep,name=service_accounts,json=serviceAccounts,proto3" json:"service_accounts,omitempty"`
	// Pagination token for the next page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountsResponse) Reset() {
	*x = ListServiceAccountsResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountsResponse) ProtoMessage() {}

func (x *ListServiceAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListServiceAccountsResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{6}
}

func (x *ListServiceAccountsResponse) GetServiceAccounts() []*ServiceAccount {
	if x != nil {
		return x.ServiceAccounts
	}
	return nil
}

func (x *ListServiceAccountsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// UpdateServiceAccountRequest contains the service account fields to update.
type UpdateServiceAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account with updated fields. The `id` field is required
	// to identify the resource. Only fields specified in `update_mask` are updated.
	ServiceAccount *ServiceAccount `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// The set of fields to update. If unset, all mutable fields are updated.
	// Supported fields: `display_name`, `description`, `scopes`, `status`.
	UpdateMask    *fieldmaskpb.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateServiceAccountRequest) Reset() {
	*x = UpdateServiceAccountRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountRequest) ProtoMessage() {}

func (x *UpdateServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateServiceAccountRequest) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *UpdateServiceAccountRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

// UpdateServiceAccountResponse contains the updated service account.
type UpdateServiceAccountResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated service account.
	ServiceAccount *ServiceAccount `protobuf:"bytes,1,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateServiceAccountResponse) Reset() {
	*x = UpdateServiceAccountResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateServiceAccountResponse) ProtoMessage() {}

func (x *UpdateServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateServiceAccountResponse) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

// DeleteServiceAccountRequest identifies a service account to delete.
type DeleteServiceAccountRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the service account to delete (UUID).
	// All associated SATs will be revoked.
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeleteServiceAccountRequest) Reset() {
	*x = DeleteServiceAccountRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountRequest) ProtoMessage() {}

func (x *DeleteServiceAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServiceAccountRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

// DeleteServiceAccountResponse is empty on success.
type DeleteServiceAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceAccountResponse) Reset() {
	*x = DeleteServiceAccountResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceAccountResponse) ProtoMessage() {}

func (x *DeleteServiceAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceAccountResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{10}
}

// CreateServiceAccountTokenRequest contains the parameters for creating a new SAT.
type CreateServiceAccountTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account to create the token under (UUID).
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// Human-readable name for the token (e.g., "github-actions-key").
	// Must be unique per service account.
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// The scopes to grant this token. Must be a subset of the parent service
	// account's allowed scopes.
	Scopes []string `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Optional expiration time. If unset, the token does not expire.
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateServiceAccountTokenRequest) Reset() {
	*x = CreateServiceAccountTokenRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountTokenRequest) ProtoMessage() {}

func (x *CreateServiceAccountTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountTokenRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{11}
}

func (x *CreateServiceAccountTokenRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *CreateServiceAccountTokenRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateServiceAccountTokenRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *CreateServiceAccountTokenRequest) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

// CreateServiceAccountTokenResponse contains the newly created SAT.
type CreateServiceAccountTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created token metadata.
	AccessToken *v1.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	// The raw token secret (e.g., "adm_sat_mJ4nP7qR9sT2..."). This value is
	// shown exactly once and cannot be retrieved again. Store it securely.
	PlainTextToken string `protobuf:"bytes,2,opt,name=plain_text_token,json=plainTextToken,proto3" json:"plain_text_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateServiceAccountTokenResponse) Reset() {
	*x = CreateServiceAccountTokenResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateServiceAccountTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateServiceAccountTokenResponse) ProtoMessage() {}

func (x *CreateServiceAccountTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateServiceAccountTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateServiceAccountTokenResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{12}
}

func (x *CreateServiceAccountTokenResponse) GetAccessToken() *v1.AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

func (x *CreateServiceAccountTokenResponse) GetPlainTextToken() string {
	if x != nil {
		return x.PlainTextToken
	}
	return ""
}

// ListServiceAccountTokensRequest contains pagination and filter parameters.
type ListServiceAccountTokensRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account whose tokens to list (UUID).
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// Maximum number of tokens to return per page.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque pagination token from a previous response.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter expression using the PEG filter DSL.
	Filter        string `protobuf:"bytes,4,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountTokensRequest) Reset() {
	*x = ListServiceAccountTokensRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountTokensRequest) ProtoMessage() {}

func (x *ListServiceAccountTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountTokensRequest.ProtoReflect.Descriptor instead.
func (*ListServiceAccountTokensRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{13}
}

func (x *ListServiceAccountTokensRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *ListServiceAccountTokensRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListServiceAccountTokensRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListServiceAccountTokensRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ListServiceAccountTokensResponse contains a page of SAT metadata.
type ListServiceAccountTokensResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of tokens. Token secrets are never included.
	AccessTokens []*v1.AccessToken `protobuf:"bytes,1,rep,name=access_tokens,json=accessTokens,proto3" json:"access_tokens,omitempty"`
	// Pagination token for the next page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServiceAccountTokensResponse) Reset() {
	*x = ListServiceAccountTokensResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServiceAccountTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServiceAccountTokensResponse) ProtoMessage() {}

func (x *ListServiceAccountTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServiceAccountTokensResponse.ProtoReflect.Descriptor instead.
func (*ListServiceAccountTokensResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{14}
}

func (x *ListServiceAccountTokensResponse) GetAccessTokens() []*v1.AccessToken {
	if x != nil {
		return x.AccessTokens
	}
	return nil
}

func (x *ListServiceAccountTokensResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetServiceAccountTokenRequest identifies a SAT to retrieve.
type GetServiceAccountTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account the token belongs to (UUID).
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// The unique identifier of the token (UUID).
	TokenId       string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceAccountTokenRequest) Reset() {
	*x = GetServiceAccountTokenRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountTokenRequest) ProtoMessage() {}

func (x *GetServiceAccountTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountTokenRequest.ProtoReflect.Descriptor instead.
func (*GetServiceAccountTokenRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{15}
}

func (x *GetServiceAccountTokenRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *GetServiceAccountTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// GetServiceAccountTokenResponse contains the requested SAT metadata.
type GetServiceAccountTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token metadata. The token secret is never included.
	AccessToken   *v1.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServiceAccountTokenResponse) Reset() {
	*x = GetServiceAccountTokenResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServiceAccountTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServiceAccountTokenResponse) ProtoMessage() {}

func (x *GetServiceAccountTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServiceAccountTokenResponse.ProtoReflect.Descriptor instead.
func (*GetServiceAccountTokenResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{16}
}

func (x *GetServiceAccountTokenResponse) GetAccessToken() *v1.AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

// RevokeServiceAccountTokenRequest identifies a SAT to revoke.
type RevokeServiceAccountTokenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The service account the token belongs to (UUID).
	ServiceAccountId string `protobuf:"bytes,1,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// The unique identifier of the token to revoke (UUID).
	TokenId       string `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceAccountTokenRequest) Reset() {
	*x = RevokeServiceAccountTokenRequest{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountTokenRequest) ProtoMessage() {}

func (x *RevokeServiceAccountTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountTokenRequest) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{17}
}

func (x *RevokeServiceAccountTokenRequest) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *RevokeServiceAccountTokenRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

// RevokeServiceAccountTokenResponse contains the revoked SAT metadata.
type RevokeServiceAccountTokenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The token metadata with updated status.
	AccessToken   *v1.AccessToken `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeServiceAccountTokenResponse) Reset() {
	*x = RevokeServiceAccountTokenResponse{}
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeServiceAccountTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeServiceAccountTokenResponse) ProtoMessage() {}

func (x *RevokeServiceAccountTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_serviceaccount_v1_serviceaccount_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeServiceAccountTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeServiceAccountTokenResponse) Descriptor() ([]byte, []int) {
	return file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP(), []int{18}
}

func (x *RevokeServiceAccountTokenResponse) GetAccessToken() *v1.AccessToken {
	if x != nil {
		return x.AccessToken
	}
	return nil
}

var File_serviceaccount_v1_serviceaccount_proto protoreflect.FileDescriptor

const file_serviceaccount_v1_serviceaccount_proto_rawDesc = "" +
	"\n" +
	"&serviceaccount/v1/serviceaccount.proto\x12\x1dadmiral.api.serviceaccount.v1\x1a accesstoken/v1/accesstoken.proto\x1a\x1aauthz/v1/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x03\n" +
	"\x0eServiceAccount\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\ttenant_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12-\n" +
	"\fdisplay_name\x18\x03 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06scopes\x18\x05 \x03(\tR\x06scopes\x12K\n" +
	"\x06status\x18\x06 \x01(\x0e23.admiral.api.serviceaccount.v1.ServiceAccountStatusR\x06status\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x86\x01\n" +
	"\x1bCreateServiceAccountRequest\x12-\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"v\n" +
	"\x1cCreateServiceAccountResponse\x12V\n" +
	"\x0fservice_account\x18\x01 \x01(\v2-.admiral.api.serviceaccount.v1.ServiceAccountR\x0eserviceAccount\"R\n" +
	"\x18GetServiceAccountRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\"s\n" +
	"\x19GetServiceAccountResponse\x12V\n" +
	"\x0fservice_account\x18\x01 \x01(\v2-.admiral.api.serviceaccount.v1.ServiceAccountR\x0eserviceAccount\"p\n" +
	"\x1aListServiceAccountsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"\x9f\x01\n" +
	"\x1bListServiceAccountsResponse\x12X\n" +
	"\x10service_accounts\x18\x01 \x03(\v2-.admiral.api.serviceaccount.v1.ServiceAccountR\x0fserviceAccounts\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xba\x01\n" +
	"\x1bUpdateServiceAccountRequest\x12^\n" +
	"\x0fservice_account\x18\x01 \x01(\v2-.admiral.api.serviceaccount.v1.ServiceAccountB\x06\xbaH\x03\xc8\x01\x01R\x0eserviceAccount\x12;\n" +
	"\vupdate_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\"v\n" +
	"\x1cUpdateServiceAccountResponse\x12V\n" +
	"\x0fservice_account\x18\x01 \x01(\v2-.admiral.api.serviceaccount.v1.ServiceAccountR\x0eserviceAccount\"U\n" +
	"\x1bDeleteServiceAccountRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\"\x1e\n" +
	"\x1cDeleteServiceAccountResponse\"\xdc\x01\n" +
	" CreateServiceAccountTokenRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\x12-\n" +
	"\fdisplay_name\x18\x02 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"expires_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x99\x01\n" +
	"!CreateServiceAccountTokenResponse\x12J\n" +
	"\faccess_token\x18\x01 \x01(\v2'.admiral.api.accesstoken.v1.AccessTokenR\vaccessToken\x12(\n" +
	"\x10plain_text_token\x18\x02 \x01(\tR\x0eplainTextToken\"\xad\x01\n" +
	"\x1fListServiceAccountTokensRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\tR\x06filter\"\x98\x01\n" +
	" ListServiceAccountTokensResponse\x12L\n" +
	"\raccess_tokens\x18\x01 \x03(\v2'.admiral.api.accesstoken.v1.AccessTokenR\faccessTokens\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"|\n" +
	"\x1dGetServiceAccountTokenRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\x12#\n" +
	"\btoken_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\atokenId\"l\n" +
	"\x1eGetServiceAccountTokenResponse\x12J\n" +
	"\faccess_token\x18\x01 \x01(\v2'.admiral.api.accesstoken.v1.AccessTokenR\vaccessToken\"\x7f\n" +
	" RevokeServiceAccountTokenRequest\x126\n" +
	"\x12service_account_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x10serviceAccountId\x12#\n" +
	"\btoken_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\atokenId\"o\n" +
	"!RevokeServiceAccountTokenResponse\x12J\n" +
	"\faccess_token\x18\x01 \x01(\v2'.admiral.api.accesstoken.v1.AccessTokenR\vaccessToken*\x86\x01\n" +
	"\x14ServiceAccountStatus\x12&\n" +
	"\"SERVICE_ACCOUNT_STATUS_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dSERVICE_ACCOUNT_STATUS_ACTIVE\x10\x01\x12#\n" +
	"\x1fSERVICE_ACCOUNT_STATUS_DISABLED\x10\x022\xb9\x0f\n" +
	"\x11ServiceAccountAPI\x12\xbe\x01\n" +
	"\x14CreateServiceAccount\x12:.admiral.api.serviceaccount.v1.CreateServiceAccountRequest\x1a;.admiral.api.serviceaccount.v1.CreateServiceAccountResponse\"-\x82\xb5\x18\n" +
	"\n" +
	"\bsa:write\x82\xd3\xe4\x93\x02\x19:\x01*\"\x14/v1/service-accounts\x12\xc6\x01\n" +
	"\x11GetServiceAccount\x127.admiral.api.serviceaccount.v1.GetServiceAccountRequest\x1a8.admiral.api.serviceaccount.v1.GetServiceAccountResponse\">\x82\xb5\x18\t\n" +
	"\asa:read\x82\xd3\xe4\x93\x02+\x12)/v1/service-accounts/{service_account_id}\x12\xb7\x01\n" +
	"\x13ListServiceAccounts\x129.admiral.api.serviceaccount.v1.ListServiceAccountsRequest\x1a:.admiral.api.serviceaccount.v1.ListServiceAccountsResponse\")\x82\xb5\x18\t\n" +
	"\asa:read\x82\xd3\xe4\x93\x02\x16\x12\x14/v1/service-accounts\x12\xd3\x01\n" +
	"\x14UpdateServiceAccount\x12:.admiral.api.serviceaccount.v1.UpdateServiceAccountRequest\x1a;.admiral.api.serviceaccount.v1.UpdateServiceAccountResponse\"B\x82\xb5\x18\n" +
	"\n" +
	"\bsa:write\x82\xd3\xe4\x93\x02.:\x01*2)/v1/service-accounts/{service_account.id}\x12\xd0\x01\n" +
	"\x14DeleteServiceAccount\x12:.admiral.api.serviceaccount.v1.DeleteServiceAccountRequest\x1a;.admiral.api.serviceaccount.v1.DeleteServiceAccountResponse\"?\x82\xb5\x18\n" +
	"\n" +
	"\bsa:write\x82\xd3\xe4\x93\x02+*)/v1/service-accounts/{service_account_id}\x12\xe9\x01\n" +
	"\x19CreateServiceAccountToken\x12?.admiral.api.serviceaccount.v1.CreateServiceAccountTokenRequest\x1a@.admiral.api.serviceaccount.v1.CreateServiceAccountTokenResponse\"I\x82\xb5\x18\n" +
	"\n" +
	"\bsa:write\x82\xd3\xe4\x93\x025:\x01*\"0/v1/service-accounts/{service_account_id}/tokens\x12\xe2\x01\n" +
	"\x18ListServiceAccountTokens\x12>.admiral.api.serviceaccount.v1.ListServiceAccountTokensRequest\x1a?.admiral.api.serviceaccount.v1.ListServiceAccountTokensResponse\"E\x82\xb5\x18\t\n" +
	"\asa:read\x82\xd3\xe4\x93\x022\x120/v1/service-accounts/{service_account_id}/tokens\x12\xe7\x01\n" +
	"\x16GetServiceAccountToken\x12<.admiral.api.serviceaccount.v1.GetServiceAccountTokenRequest\x1a=.admiral.api.serviceaccount.v1.GetServiceAccountTokenResponse\"P\x82\xb5\x18\t\n" +
	"\asa:read\x82\xd3\xe4\x93\x02=\x12;/v1/service-accounts/{service_account_id}/tokens/{token_id}\x12\xfb\x01\n" +
	"\x19RevokeServiceAccountToken\x12?.admiral.api.serviceaccount.v1.RevokeServiceAccountTokenRequest\x1a@.admiral.api.serviceaccount.v1.RevokeServiceAccountTokenResponse\"[\x82\xb5\x18\n" +
	"\n" +
	"\bsa:write\x82\xd3\xe4\x93\x02G:\x01*\"B/v1/service-accounts/{service_account_id}/tokens/{token_id}/revokeB\x8b\x02\n" +
	"!com.admiral.api.serviceaccount.v1B\x13ServiceaccountProtoP\x01Z:go.admiral.io/sdk/proto/serviceaccount/v1;serviceaccountv1\xa2\x02\x03AAS\xaa\x02\x1dAdmiral.Api.Serviceaccount.V1\xca\x02\x1dAdmiral\\Api\\Serviceaccount\\V1\xe2\x02)Admiral\\Api\\Serviceaccount\\V1\\GPBMetadata\xea\x02 Admiral::Api::Serviceaccount::V1b\x06proto3"

var (
	file_serviceaccount_v1_serviceaccount_proto_rawDescOnce sync.Once
	file_serviceaccount_v1_serviceaccount_proto_rawDescData []byte
)

func file_serviceaccount_v1_serviceaccount_proto_rawDescGZIP() []byte {
	file_serviceaccount_v1_serviceaccount_proto_rawDescOnce.Do(func() {
		file_serviceaccount_v1_serviceaccount_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_serviceaccount_v1_serviceaccount_proto_rawDesc), len(file_serviceaccount_v1_serviceaccount_proto_rawDesc)))
	})
	return file_serviceaccount_v1_serviceaccount_proto_rawDescData
}

var file_serviceaccount_v1_serviceaccount_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_serviceaccount_v1_serviceaccount_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_serviceaccount_v1_serviceaccount_proto_goTypes = []any{
	(ServiceAccountStatus)(0),                 // 0: admiral.api.serviceaccount.v1.ServiceAccountStatus
	(*ServiceAccount)(nil),                    // 1: admiral.api.serviceaccount.v1.ServiceAccount
	(*CreateServiceAccountRequest)(nil),       // 2: admiral.api.serviceaccount.v1.CreateServiceAccountRequest
	(*CreateServiceAccountResponse)(nil),      // 3: admiral.api.serviceaccount.v1.CreateServiceAccountResponse
	(*GetServiceAccountRequest)(nil),          // 4: admiral.api.serviceaccount.v1.GetServiceAccountRequest
	(*GetServiceAccountResponse)(nil),         // 5: admiral.api.serviceaccount.v1.GetServiceAccountResponse
	(*ListServiceAccountsRequest)(nil),        // 6: admiral.api.serviceaccount.v1.ListServiceAccountsRequest
	(*ListServiceAccountsResponse)(nil),       // 7: admiral.api.serviceaccount.v1.ListServiceAccountsResponse
	(*UpdateServiceAccountRequest)(nil),       // 8: admiral.api.serviceaccount.v1.UpdateServiceAccountRequest
	(*UpdateServiceAccountResponse)(nil),      // 9: admiral.api.serviceaccount.v1.UpdateServiceAccountResponse
	(*DeleteServiceAccountRequest)(nil),       // 10: admiral.api.serviceaccount.v1.DeleteServiceAccountRequest
	(*DeleteServiceAccountResponse)(nil),      // 11: admiral.api.serviceaccount.v1.DeleteServiceAccountResponse
	(*CreateServiceAccountTokenRequest)(nil),  // 12: admiral.api.serviceaccount.v1.CreateServiceAccountTokenRequest
	(*CreateServiceAccountTokenResponse)(nil), // 13: admiral.api.serviceaccount.v1.CreateServiceAccountTokenResponse
	(*ListServiceAccountTokensRequest)(nil),   // 14: admiral.api.serviceaccount.v1.ListServiceAccountTokensRequest
	(*ListServiceAccountTokensResponse)(nil),  // 15: admiral.api.serviceaccount.v1.ListServiceAccountTokensResponse
	(*GetServiceAccountTokenRequest)(nil),     // 16: admiral.api.serviceaccount.v1.GetServiceAccountTokenRequest
	(*GetServiceAccountTokenResponse)(nil),    // 17: admiral.api.serviceaccount.v1.GetServiceAccountTokenResponse
	(*RevokeServiceAccountTokenRequest)(nil),  // 18: admiral.api.serviceaccount.v1.RevokeServiceAccountTokenRequest
	(*RevokeServiceAccountTokenResponse)(nil), // 19: admiral.api.serviceaccount.v1.RevokeServiceAccountTokenResponse
	(*timestamppb.Timestamp)(nil),             // 20: google.protobuf.Timestamp
	(*fieldmaskpb.FieldMask)(nil),             // 21: google.protobuf.FieldMask
	(*v1.AccessToken)(nil),                    // 22: admiral.api.accesstoken.v1.AccessToken
}
var file_serviceaccount_v1_serviceaccount_proto_depIdxs = []int32{
	0,  // 0: admiral.api.serviceaccount.v1.ServiceAccount.status:type_name -> admiral.api.serviceaccount.v1.ServiceAccountStatus
	20, // 1: admiral.api.serviceaccount.v1.ServiceAccount.created_at:type_name -> google.protobuf.Timestamp
	20, // 2: admiral.api.serviceaccount.v1.ServiceAccount.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 3: admiral.api.serviceaccount.v1.CreateServiceAccountResponse.service_account:type_name -> admiral.api.serviceaccount.v1.ServiceAccount
	1,  // 4: admiral.api.serviceaccount.v1.GetServiceAccountResponse.service_account:type_name -> admiral.api.serviceaccount.v1.ServiceAccount
	1,  // 5: admiral.api.serviceaccount.v1.ListServiceAccountsResponse.service_accounts:type_name -> admiral.api.serviceaccount.v1.ServiceAccount
	1,  // 6: admiral.api.serviceaccount.v1.UpdateServiceAccountRequest.service_account:type_name -> admiral.api.serviceaccount.v1.ServiceAccount
	21, // 7: admiral.api.serviceaccount.v1.UpdateServiceAccountRequest.update_mask:type_name -> google.protobuf.FieldMask
	1,  // 8: admiral.api.serviceaccount.v1.UpdateServiceAccountResponse.service_account:type_name -> admiral.api.serviceaccount.v1.ServiceAccount
	20, // 9: admiral.api.serviceaccount.v1.CreateServiceAccountTokenRequest.expires_at:type_name -> google.protobuf.Timestamp
	22, // 10: admiral.api.serviceaccount.v1.CreateServiceAccountTokenResponse.access_token:type_name -> admiral.api.accesstoken.v1.AccessToken
	22, // 11: admiral.api.serviceaccount.v1.ListServiceAccountTokensResponse.access_tokens:type_name -> admiral.api.accesstoken.v1.AccessToken
	22, // 12: admiral.api.serviceaccount.v1.GetServiceAccountTokenResponse.access_token:type_name -> admiral.api.accesstoken.v1.AccessToken
	22, // 13: admiral.api.serviceaccount.v1.RevokeServiceAccountTokenResponse.access_token:type_name -> admiral.api.accesstoken.v1.AccessToken
	2,  // 14: admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccount:input_type -> admiral.api.serviceaccount.v1.CreateServiceAccountRequest
	4,  // 15: admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccount:input_type -> admiral.api.serviceaccount.v1.GetServiceAccountRequest
	6,  // 16: admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccounts:input_type -> admiral.api.serviceaccount.v1.ListServiceAccountsRequest
	8,  // 17: admiral.api.serviceaccount.v1.ServiceAccountAPI.UpdateServiceAccount:input_type -> admiral.api.serviceaccount.v1.UpdateServiceAccountRequest
	10, // 18: admiral.api.serviceaccount.v1.ServiceAccountAPI.DeleteServiceAccount:input_type -> admiral.api.serviceaccount.v1.DeleteServiceAccountRequest
	12, // 19: admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccountToken:input_type -> admiral.api.serviceaccount.v1.CreateServiceAccountTokenRequest
	14, // 20: admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccountTokens:input_type -> admiral.api.serviceaccount.v1.ListServiceAccountTokensRequest
	16, // 21: admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccountToken:input_type -> admiral.api.serviceaccount.v1.GetServiceAccountTokenRequest
	18, // 22: admiral.api.serviceaccount.v1.ServiceAccountAPI.RevokeServiceAccountToken:input_type -> admiral.api.serviceaccount.v1.RevokeServiceAccountTokenRequest
	3,  // 23: admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccount:output_type -> admiral.api.serviceaccount.v1.CreateServiceAccountResponse
	5,  // 24: admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccount:output_type -> admiral.api.serviceaccount.v1.GetServiceAccountResponse
	7,  // 25: admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccounts:output_type -> admiral.api.serviceaccount.v1.ListServiceAccountsResponse
	9,  // 26: admiral.api.serviceaccount.v1.ServiceAccountAPI.UpdateServiceAccount:output_type -> admiral.api.serviceaccount.v1.UpdateServiceAccountResponse
	11, // 27: admiral.api.serviceaccount.v1.ServiceAccountAPI.DeleteServiceAccount:output_type -> admiral.api.serviceaccount.v1.DeleteServiceAccountResponse
	13, // 28: admiral.api.serviceaccount.v1.ServiceAccountAPI.CreateServiceAccountToken:output_type -> admiral.api.serviceaccount.v1.CreateServiceAccountTokenResponse
	15, // 29: admiral.api.serviceaccount.v1.ServiceAccountAPI.ListServiceAccountTokens:output_type -> admiral.api.serviceaccount.v1.ListServiceAccountTokensResponse
	17, // 30: admiral.api.serviceaccount.v1.ServiceAccountAPI.GetServiceAccountToken:output_type -> admiral.api.serviceaccount.v1.GetServiceAccountTokenResponse
	19, // 31: admiral.api.serviceaccount.v1.ServiceAccountAPI.RevokeServiceAccountToken:output_type -> admiral.api.serviceaccount.v1.RevokeServiceAccountTokenResponse
	23, // [23:32] is the sub-list for method output_type
	14, // [14:23] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_serviceaccount_v1_serviceaccount_proto_init() }
func file_serviceaccount_v1_serviceaccount_proto_init() {
	if File_serviceaccount_v1_serviceaccount_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_serviceaccount_v1_serviceaccount_proto_rawDesc), len(file_serviceaccount_v1_serviceaccount_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_serviceaccount_v1_serviceaccount_proto_goTypes,
		DependencyIndexes: file_serviceaccount_v1_serviceaccount_proto_depIdxs,
		EnumInfos:         file_serviceaccount_v1_serviceaccount_proto_enumTypes,
		MessageInfos:      file_serviceaccount_v1_serviceaccount_proto_msgTypes,
	}.Build()
	File_serviceaccount_v1_serviceaccount_proto = out.File
	file_serviceaccount_v1_serviceaccount_proto_goTypes = nil
	file_serviceaccount_v1_serviceaccount_proto_depIdxs = nil
}
