// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: accesstoken/v1/accesstoken.proto

package accesstokenv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "go.admiral.io/sdk/proto/authz/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AccessTokenStatus represents the lifecycle state of an access token.
type AccessTokenStatus int32

const (
	// Default value. Must not be used.
	AccessTokenStatus_ACCESS_TOKEN_STATUS_UNSPECIFIED AccessTokenStatus = 0
	// The token is valid and can be used for authentication.
	AccessTokenStatus_ACCESS_TOKEN_STATUS_ACTIVE AccessTokenStatus = 1
	// The token has been permanently revoked and cannot be used.
	AccessTokenStatus_ACCESS_TOKEN_STATUS_REVOKED AccessTokenStatus = 2
	// The token is being rotated. Both old and new tokens are valid
	// until the grace period expires.
	AccessTokenStatus_ACCESS_TOKEN_STATUS_ROTATING AccessTokenStatus = 3
)

// Enum value maps for AccessTokenStatus.
var (
	AccessTokenStatus_name = map[int32]string{
		0: "ACCESS_TOKEN_STATUS_UNSPECIFIED",
		1: "ACCESS_TOKEN_STATUS_ACTIVE",
		2: "ACCESS_TOKEN_STATUS_REVOKED",
		3: "ACCESS_TOKEN_STATUS_ROTATING",
	}
	AccessTokenStatus_value = map[string]int32{
		"ACCESS_TOKEN_STATUS_UNSPECIFIED": 0,
		"ACCESS_TOKEN_STATUS_ACTIVE":      1,
		"ACCESS_TOKEN_STATUS_REVOKED":     2,
		"ACCESS_TOKEN_STATUS_ROTATING":    3,
	}
)

func (x AccessTokenStatus) Enum() *AccessTokenStatus {
	p := new(AccessTokenStatus)
	*p = x
	return p
}

func (x AccessTokenStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessTokenStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_accesstoken_v1_accesstoken_proto_enumTypes[0].Descriptor()
}

func (AccessTokenStatus) Type() protoreflect.EnumType {
	return &file_accesstoken_v1_accesstoken_proto_enumTypes[0]
}

func (x AccessTokenStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessTokenStatus.Descriptor instead.
func (AccessTokenStatus) EnumDescriptor() ([]byte, []int) {
	return file_accesstoken_v1_accesstoken_proto_rawDescGZIP(), []int{0}
}

// AccessToken contains token metadata common to all token types (PAT, SAT, AGT).
// The raw token secret is never included in this message — it is only returned
// once at creation time via the `plain_text_token` field in Create responses.
//
// Token CRUD is managed by each parent resource's API:
//   - PATs:         UserAPI            (/v1/user/tokens)
//   - SATs:         ServiceAccountAPI  (/v1/service-accounts/{id}/tokens)
//   - Cluster AGTs: ClusterAPI         (/v1/clusters/{id}/tokens)
//   - Runner AGTs:  RunnerAPI          (/v1/runners/{id}/tokens)
type AccessToken struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the token (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant this token belongs to (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Human-readable name for the token (e.g., "postman-testing", "ci-deploy-key").
	DisplayName string `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Display-safe prefix for identifying the token without exposing the secret
	// (e.g., "adm_pat_7kH3").
	TokenPrefix string `protobuf:"bytes,4,opt,name=token_prefix,json=tokenPrefix,proto3" json:"token_prefix,omitempty"`
	// The category of this token.
	TokenType v1.TokenType `protobuf:"varint,5,opt,name=token_type,json=tokenType,proto3,enum=admiral.api.authz.v1.TokenType" json:"token_type,omitempty"`
	// The scopes granted to this token. For PATs and SATs, these are user-selected.
	// For AGTs, these are auto-assigned based on the resource type.
	Scopes []string `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// Current lifecycle status of the token.
	Status AccessTokenStatus `protobuf:"varint,7,opt,name=status,proto3,enum=admiral.api.accesstoken.v1.AccessTokenStatus" json:"status,omitempty"`
	// The user this token is bound to (UUID). Set when token_type is
	// PERSONAL_ACCESS_TOKEN.
	UserId string `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// The service account this token is bound to (UUID). Set when token_type is
	// SERVICE_ACCOUNT_TOKEN.
	ServiceAccountId string `protobuf:"bytes,9,opt,name=service_account_id,json=serviceAccountId,proto3" json:"service_account_id,omitempty"`
	// The cluster this token is bound to (UUID). Set when token_type is
	// AGENT_TOKEN and the token is bound to a cluster.
	ClusterId string `protobuf:"bytes,10,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// The runner this token is bound to (UUID). Set when token_type is
	// AGENT_TOKEN and the token is bound to a runner.
	RunnerId string `protobuf:"bytes,11,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	// The user who created this token (UUID). For PATs, this is the token owner.
	// For SATs and AGTs, this is the administrator who issued the token.
	CreatedBy string `protobuf:"bytes,12,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// When the token expires. If unset, the token does not expire.
	ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	// When the token was last used to authenticate an API request.
	LastUsedAt *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=last_used_at,json=lastUsedAt,proto3" json:"last_used_at,omitempty"`
	// When the token was created.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the token was revoked. Only set when status is REVOKED.
	RevokedAt     *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessToken) Reset() {
	*x = AccessToken{}
	mi := &file_accesstoken_v1_accesstoken_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessToken) ProtoMessage() {}

func (x *AccessToken) ProtoReflect() protoreflect.Message {
	mi := &file_accesstoken_v1_accesstoken_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessToken.ProtoReflect.Descriptor instead.
func (*AccessToken) Descriptor() ([]byte, []int) {
	return file_accesstoken_v1_accesstoken_proto_rawDescGZIP(), []int{0}
}

func (x *AccessToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccessToken) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *AccessToken) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *AccessToken) GetTokenPrefix() string {
	if x != nil {
		return x.TokenPrefix
	}
	return ""
}

func (x *AccessToken) GetTokenType() v1.TokenType {
	if x != nil {
		return x.TokenType
	}
	return v1.TokenType(0)
}

func (x *AccessToken) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *AccessToken) GetStatus() AccessTokenStatus {
	if x != nil {
		return x.Status
	}
	return AccessTokenStatus_ACCESS_TOKEN_STATUS_UNSPECIFIED
}

func (x *AccessToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccessToken) GetServiceAccountId() string {
	if x != nil {
		return x.ServiceAccountId
	}
	return ""
}

func (x *AccessToken) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *AccessToken) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *AccessToken) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AccessToken) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *AccessToken) GetLastUsedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsedAt
	}
	return nil
}

func (x *AccessToken) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccessToken) GetRevokedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.RevokedAt
	}
	return nil
}

var File_accesstoken_v1_accesstoken_proto protoreflect.FileDescriptor

const file_accesstoken_v1_accesstoken_proto_rawDesc = "" +
	"\n" +
	" accesstoken/v1/accesstoken.proto\x12\x1aadmiral.api.accesstoken.v1\x1a\x1aauthz/v1/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc4\x05\n" +
	"\vAccessToken\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\ttenant_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12!\n" +
	"\ftoken_prefix\x18\x04 \x01(\tR\vtokenPrefix\x12>\n" +
	"\n" +
	"token_type\x18\x05 \x01(\x0e2\x1f.admiral.api.authz.v1.TokenTypeR\ttokenType\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x12E\n" +
	"\x06status\x18\a \x01(\x0e2-.admiral.api.accesstoken.v1.AccessTokenStatusR\x06status\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\x12,\n" +
	"\x12service_account_id\x18\t \x01(\tR\x10serviceAccountId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\n" +
	" \x01(\tR\tclusterId\x12\x1b\n" +
	"\trunner_id\x18\v \x01(\tR\brunnerId\x12\x1d\n" +
	"\n" +
	"created_by\x18\f \x01(\tR\tcreatedBy\x129\n" +
	"\n" +
	"expires_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12<\n" +
	"\flast_used_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"lastUsedAt\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"revoked_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\trevokedAt*\x9b\x01\n" +
	"\x11AccessTokenStatus\x12#\n" +
	"\x1fACCESS_TOKEN_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aACCESS_TOKEN_STATUS_ACTIVE\x10\x01\x12\x1f\n" +
	"\x1bACCESS_TOKEN_STATUS_REVOKED\x10\x02\x12 \n" +
	"\x1cACCESS_TOKEN_STATUS_ROTATING\x10\x03B\xf3\x01\n" +
	"\x1ecom.admiral.api.accesstoken.v1B\x10AccesstokenProtoP\x01Z4go.admiral.io/sdk/proto/accesstoken/v1;accesstokenv1\xa2\x02\x03AAA\xaa\x02\x1aAdmiral.Api.Accesstoken.V1\xca\x02\x1aAdmiral\\Api\\Accesstoken\\V1\xe2\x02&Admiral\\Api\\Accesstoken\\V1\\GPBMetadata\xea\x02\x1dAdmiral::Api::Accesstoken::V1b\x06proto3"

var (
	file_accesstoken_v1_accesstoken_proto_rawDescOnce sync.Once
	file_accesstoken_v1_accesstoken_proto_rawDescData []byte
)

func file_accesstoken_v1_accesstoken_proto_rawDescGZIP() []byte {
	file_accesstoken_v1_accesstoken_proto_rawDescOnce.Do(func() {
		file_accesstoken_v1_accesstoken_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accesstoken_v1_accesstoken_proto_rawDesc), len(file_accesstoken_v1_accesstoken_proto_rawDesc)))
	})
	return file_accesstoken_v1_accesstoken_proto_rawDescData
}

var file_accesstoken_v1_accesstoken_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_accesstoken_v1_accesstoken_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_accesstoken_v1_accesstoken_proto_goTypes = []any{
	(AccessTokenStatus)(0),        // 0: admiral.api.accesstoken.v1.AccessTokenStatus
	(*AccessToken)(nil),           // 1: admiral.api.accesstoken.v1.AccessToken
	(v1.TokenType)(0),             // 2: admiral.api.authz.v1.TokenType
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_accesstoken_v1_accesstoken_proto_depIdxs = []int32{
	2, // 0: admiral.api.accesstoken.v1.AccessToken.token_type:type_name -> admiral.api.authz.v1.TokenType
	0, // 1: admiral.api.accesstoken.v1.AccessToken.status:type_name -> admiral.api.accesstoken.v1.AccessTokenStatus
	3, // 2: admiral.api.accesstoken.v1.AccessToken.expires_at:type_name -> google.protobuf.Timestamp
	3, // 3: admiral.api.accesstoken.v1.AccessToken.last_used_at:type_name -> google.protobuf.Timestamp
	3, // 4: admiral.api.accesstoken.v1.AccessToken.created_at:type_name -> google.protobuf.Timestamp
	3, // 5: admiral.api.accesstoken.v1.AccessToken.revoked_at:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_accesstoken_v1_accesstoken_proto_init() }
func file_accesstoken_v1_accesstoken_proto_init() {
	if File_accesstoken_v1_accesstoken_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accesstoken_v1_accesstoken_proto_rawDesc), len(file_accesstoken_v1_accesstoken_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accesstoken_v1_accesstoken_proto_goTypes,
		DependencyIndexes: file_accesstoken_v1_accesstoken_proto_depIdxs,
		EnumInfos:         file_accesstoken_v1_accesstoken_proto_enumTypes,
		MessageInfos:      file_accesstoken_v1_accesstoken_proto_msgTypes,
	}.Build()
	File_accesstoken_v1_accesstoken_proto = out.File
	file_accesstoken_v1_accesstoken_proto_goTypes = nil
	file_accesstoken_v1_accesstoken_proto_depIdxs = nil
}
