// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: runner/v1/runner.proto

package runnerv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/sdk/proto/runner/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RunnerAPIName is the fully-qualified name of the RunnerAPI service.
	RunnerAPIName = "admiral.api.runner.v1.RunnerAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RunnerAPICreateRunnerProcedure is the fully-qualified name of the RunnerAPI's CreateRunner RPC.
	RunnerAPICreateRunnerProcedure = "/admiral.api.runner.v1.RunnerAPI/CreateRunner"
	// RunnerAPIGetRunnerProcedure is the fully-qualified name of the RunnerAPI's GetRunner RPC.
	RunnerAPIGetRunnerProcedure = "/admiral.api.runner.v1.RunnerAPI/GetRunner"
	// RunnerAPIListRunnersProcedure is the fully-qualified name of the RunnerAPI's ListRunners RPC.
	RunnerAPIListRunnersProcedure = "/admiral.api.runner.v1.RunnerAPI/ListRunners"
	// RunnerAPIUpdateRunnerProcedure is the fully-qualified name of the RunnerAPI's UpdateRunner RPC.
	RunnerAPIUpdateRunnerProcedure = "/admiral.api.runner.v1.RunnerAPI/UpdateRunner"
	// RunnerAPIDeleteRunnerProcedure is the fully-qualified name of the RunnerAPI's DeleteRunner RPC.
	RunnerAPIDeleteRunnerProcedure = "/admiral.api.runner.v1.RunnerAPI/DeleteRunner"
	// RunnerAPICreateRunnerTokenProcedure is the fully-qualified name of the RunnerAPI's
	// CreateRunnerToken RPC.
	RunnerAPICreateRunnerTokenProcedure = "/admiral.api.runner.v1.RunnerAPI/CreateRunnerToken"
	// RunnerAPIListRunnerTokensProcedure is the fully-qualified name of the RunnerAPI's
	// ListRunnerTokens RPC.
	RunnerAPIListRunnerTokensProcedure = "/admiral.api.runner.v1.RunnerAPI/ListRunnerTokens"
	// RunnerAPIGetRunnerTokenProcedure is the fully-qualified name of the RunnerAPI's GetRunnerToken
	// RPC.
	RunnerAPIGetRunnerTokenProcedure = "/admiral.api.runner.v1.RunnerAPI/GetRunnerToken"
	// RunnerAPIRevokeRunnerTokenProcedure is the fully-qualified name of the RunnerAPI's
	// RevokeRunnerToken RPC.
	RunnerAPIRevokeRunnerTokenProcedure = "/admiral.api.runner.v1.RunnerAPI/RevokeRunnerToken"
)

// RunnerAPIClient is a client for the admiral.api.runner.v1.RunnerAPI service.
type RunnerAPIClient interface {
	// CreateRunner creates a new runner within the caller's tenant and generates
	// an initial Agent Token (AGT) for the controller. The response includes a
	// `plain_text_token` — the raw AGT secret shown exactly once.
	//
	// Deploy this token to the controller (e.g., via Helm values or a Kubernetes
	// Secret). The controller uses it to authenticate with AgentAPI.RegisterAgent
	// on first boot.
	//
	// Scope: `runners:write`
	CreateRunner(context.Context, *connect.Request[v1.CreateRunnerRequest]) (*connect.Response[v1.CreateRunnerResponse], error)
	// GetRunner retrieves a runner by ID.
	//
	// Scope: `runners:read`
	GetRunner(context.Context, *connect.Request[v1.GetRunnerRequest]) (*connect.Response[v1.GetRunnerResponse], error)
	// ListRunners returns a paginated list of runners within the caller's tenant.
	//
	// Scope: `runners:read`
	ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error)
	// UpdateRunner updates a runner's mutable fields (display name, labels).
	// Use the `update_mask` to specify which fields to update.
	//
	// Scope: `runners:write`
	UpdateRunner(context.Context, *connect.Request[v1.UpdateRunnerRequest]) (*connect.Response[v1.UpdateRunnerResponse], error)
	// DeleteRunner permanently deletes a runner, revokes all associated Agent
	// Tokens, and removes the agent record. Running jobs are not interrupted
	// but no new jobs will be assigned to this runner.
	//
	// Scope: `runners:write`
	DeleteRunner(context.Context, *connect.Request[v1.DeleteRunnerRequest]) (*connect.Response[v1.DeleteRunnerResponse], error)
	// CreateRunnerToken creates a new Agent Token (AGT) bound to the specified
	// runner. Scopes are auto-assigned and cannot be overridden. The response
	// includes the raw token secret, which is shown exactly once.
	//
	// Use this to create additional AGTs for an existing runner (e.g., for
	// zero-downtime token rotation). The initial AGT is created automatically
	// by CreateRunner.
	//
	// Scope: `runners:write`
	CreateRunnerToken(context.Context, *connect.Request[v1.CreateRunnerTokenRequest]) (*connect.Response[v1.CreateRunnerTokenResponse], error)
	// ListRunnerTokens returns a paginated list of AGTs bound to the specified
	// runner. Token secrets are never included.
	//
	// Scope: `runners:read`
	ListRunnerTokens(context.Context, *connect.Request[v1.ListRunnerTokensRequest]) (*connect.Response[v1.ListRunnerTokensResponse], error)
	// GetRunnerToken retrieves a single AGT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `runners:read`
	GetRunnerToken(context.Context, *connect.Request[v1.GetRunnerTokenRequest]) (*connect.Response[v1.GetRunnerTokenResponse], error)
	// RevokeRunnerToken permanently revokes an AGT bound to this runner.
	// The agent will receive a 401 on its next request. If this is the only
	// active AGT for the runner, the agent will become disconnected.
	//
	// Scope: `runners:write`
	RevokeRunnerToken(context.Context, *connect.Request[v1.RevokeRunnerTokenRequest]) (*connect.Response[v1.RevokeRunnerTokenResponse], error)
}

// NewRunnerAPIClient constructs a client for the admiral.api.runner.v1.RunnerAPI service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRunnerAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RunnerAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	runnerAPIMethods := v1.File_runner_v1_runner_proto.Services().ByName("RunnerAPI").Methods()
	return &runnerAPIClient{
		createRunner: connect.NewClient[v1.CreateRunnerRequest, v1.CreateRunnerResponse](
			httpClient,
			baseURL+RunnerAPICreateRunnerProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("CreateRunner")),
			connect.WithClientOptions(opts...),
		),
		getRunner: connect.NewClient[v1.GetRunnerRequest, v1.GetRunnerResponse](
			httpClient,
			baseURL+RunnerAPIGetRunnerProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("GetRunner")),
			connect.WithClientOptions(opts...),
		),
		listRunners: connect.NewClient[v1.ListRunnersRequest, v1.ListRunnersResponse](
			httpClient,
			baseURL+RunnerAPIListRunnersProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("ListRunners")),
			connect.WithClientOptions(opts...),
		),
		updateRunner: connect.NewClient[v1.UpdateRunnerRequest, v1.UpdateRunnerResponse](
			httpClient,
			baseURL+RunnerAPIUpdateRunnerProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("UpdateRunner")),
			connect.WithClientOptions(opts...),
		),
		deleteRunner: connect.NewClient[v1.DeleteRunnerRequest, v1.DeleteRunnerResponse](
			httpClient,
			baseURL+RunnerAPIDeleteRunnerProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("DeleteRunner")),
			connect.WithClientOptions(opts...),
		),
		createRunnerToken: connect.NewClient[v1.CreateRunnerTokenRequest, v1.CreateRunnerTokenResponse](
			httpClient,
			baseURL+RunnerAPICreateRunnerTokenProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("CreateRunnerToken")),
			connect.WithClientOptions(opts...),
		),
		listRunnerTokens: connect.NewClient[v1.ListRunnerTokensRequest, v1.ListRunnerTokensResponse](
			httpClient,
			baseURL+RunnerAPIListRunnerTokensProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("ListRunnerTokens")),
			connect.WithClientOptions(opts...),
		),
		getRunnerToken: connect.NewClient[v1.GetRunnerTokenRequest, v1.GetRunnerTokenResponse](
			httpClient,
			baseURL+RunnerAPIGetRunnerTokenProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("GetRunnerToken")),
			connect.WithClientOptions(opts...),
		),
		revokeRunnerToken: connect.NewClient[v1.RevokeRunnerTokenRequest, v1.RevokeRunnerTokenResponse](
			httpClient,
			baseURL+RunnerAPIRevokeRunnerTokenProcedure,
			connect.WithSchema(runnerAPIMethods.ByName("RevokeRunnerToken")),
			connect.WithClientOptions(opts...),
		),
	}
}

// runnerAPIClient implements RunnerAPIClient.
type runnerAPIClient struct {
	createRunner      *connect.Client[v1.CreateRunnerRequest, v1.CreateRunnerResponse]
	getRunner         *connect.Client[v1.GetRunnerRequest, v1.GetRunnerResponse]
	listRunners       *connect.Client[v1.ListRunnersRequest, v1.ListRunnersResponse]
	updateRunner      *connect.Client[v1.UpdateRunnerRequest, v1.UpdateRunnerResponse]
	deleteRunner      *connect.Client[v1.DeleteRunnerRequest, v1.DeleteRunnerResponse]
	createRunnerToken *connect.Client[v1.CreateRunnerTokenRequest, v1.CreateRunnerTokenResponse]
	listRunnerTokens  *connect.Client[v1.ListRunnerTokensRequest, v1.ListRunnerTokensResponse]
	getRunnerToken    *connect.Client[v1.GetRunnerTokenRequest, v1.GetRunnerTokenResponse]
	revokeRunnerToken *connect.Client[v1.RevokeRunnerTokenRequest, v1.RevokeRunnerTokenResponse]
}

// CreateRunner calls admiral.api.runner.v1.RunnerAPI.CreateRunner.
func (c *runnerAPIClient) CreateRunner(ctx context.Context, req *connect.Request[v1.CreateRunnerRequest]) (*connect.Response[v1.CreateRunnerResponse], error) {
	return c.createRunner.CallUnary(ctx, req)
}

// GetRunner calls admiral.api.runner.v1.RunnerAPI.GetRunner.
func (c *runnerAPIClient) GetRunner(ctx context.Context, req *connect.Request[v1.GetRunnerRequest]) (*connect.Response[v1.GetRunnerResponse], error) {
	return c.getRunner.CallUnary(ctx, req)
}

// ListRunners calls admiral.api.runner.v1.RunnerAPI.ListRunners.
func (c *runnerAPIClient) ListRunners(ctx context.Context, req *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error) {
	return c.listRunners.CallUnary(ctx, req)
}

// UpdateRunner calls admiral.api.runner.v1.RunnerAPI.UpdateRunner.
func (c *runnerAPIClient) UpdateRunner(ctx context.Context, req *connect.Request[v1.UpdateRunnerRequest]) (*connect.Response[v1.UpdateRunnerResponse], error) {
	return c.updateRunner.CallUnary(ctx, req)
}

// DeleteRunner calls admiral.api.runner.v1.RunnerAPI.DeleteRunner.
func (c *runnerAPIClient) DeleteRunner(ctx context.Context, req *connect.Request[v1.DeleteRunnerRequest]) (*connect.Response[v1.DeleteRunnerResponse], error) {
	return c.deleteRunner.CallUnary(ctx, req)
}

// CreateRunnerToken calls admiral.api.runner.v1.RunnerAPI.CreateRunnerToken.
func (c *runnerAPIClient) CreateRunnerToken(ctx context.Context, req *connect.Request[v1.CreateRunnerTokenRequest]) (*connect.Response[v1.CreateRunnerTokenResponse], error) {
	return c.createRunnerToken.CallUnary(ctx, req)
}

// ListRunnerTokens calls admiral.api.runner.v1.RunnerAPI.ListRunnerTokens.
func (c *runnerAPIClient) ListRunnerTokens(ctx context.Context, req *connect.Request[v1.ListRunnerTokensRequest]) (*connect.Response[v1.ListRunnerTokensResponse], error) {
	return c.listRunnerTokens.CallUnary(ctx, req)
}

// GetRunnerToken calls admiral.api.runner.v1.RunnerAPI.GetRunnerToken.
func (c *runnerAPIClient) GetRunnerToken(ctx context.Context, req *connect.Request[v1.GetRunnerTokenRequest]) (*connect.Response[v1.GetRunnerTokenResponse], error) {
	return c.getRunnerToken.CallUnary(ctx, req)
}

// RevokeRunnerToken calls admiral.api.runner.v1.RunnerAPI.RevokeRunnerToken.
func (c *runnerAPIClient) RevokeRunnerToken(ctx context.Context, req *connect.Request[v1.RevokeRunnerTokenRequest]) (*connect.Response[v1.RevokeRunnerTokenResponse], error) {
	return c.revokeRunnerToken.CallUnary(ctx, req)
}

// RunnerAPIHandler is an implementation of the admiral.api.runner.v1.RunnerAPI service.
type RunnerAPIHandler interface {
	// CreateRunner creates a new runner within the caller's tenant and generates
	// an initial Agent Token (AGT) for the controller. The response includes a
	// `plain_text_token` — the raw AGT secret shown exactly once.
	//
	// Deploy this token to the controller (e.g., via Helm values or a Kubernetes
	// Secret). The controller uses it to authenticate with AgentAPI.RegisterAgent
	// on first boot.
	//
	// Scope: `runners:write`
	CreateRunner(context.Context, *connect.Request[v1.CreateRunnerRequest]) (*connect.Response[v1.CreateRunnerResponse], error)
	// GetRunner retrieves a runner by ID.
	//
	// Scope: `runners:read`
	GetRunner(context.Context, *connect.Request[v1.GetRunnerRequest]) (*connect.Response[v1.GetRunnerResponse], error)
	// ListRunners returns a paginated list of runners within the caller's tenant.
	//
	// Scope: `runners:read`
	ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error)
	// UpdateRunner updates a runner's mutable fields (display name, labels).
	// Use the `update_mask` to specify which fields to update.
	//
	// Scope: `runners:write`
	UpdateRunner(context.Context, *connect.Request[v1.UpdateRunnerRequest]) (*connect.Response[v1.UpdateRunnerResponse], error)
	// DeleteRunner permanently deletes a runner, revokes all associated Agent
	// Tokens, and removes the agent record. Running jobs are not interrupted
	// but no new jobs will be assigned to this runner.
	//
	// Scope: `runners:write`
	DeleteRunner(context.Context, *connect.Request[v1.DeleteRunnerRequest]) (*connect.Response[v1.DeleteRunnerResponse], error)
	// CreateRunnerToken creates a new Agent Token (AGT) bound to the specified
	// runner. Scopes are auto-assigned and cannot be overridden. The response
	// includes the raw token secret, which is shown exactly once.
	//
	// Use this to create additional AGTs for an existing runner (e.g., for
	// zero-downtime token rotation). The initial AGT is created automatically
	// by CreateRunner.
	//
	// Scope: `runners:write`
	CreateRunnerToken(context.Context, *connect.Request[v1.CreateRunnerTokenRequest]) (*connect.Response[v1.CreateRunnerTokenResponse], error)
	// ListRunnerTokens returns a paginated list of AGTs bound to the specified
	// runner. Token secrets are never included.
	//
	// Scope: `runners:read`
	ListRunnerTokens(context.Context, *connect.Request[v1.ListRunnerTokensRequest]) (*connect.Response[v1.ListRunnerTokensResponse], error)
	// GetRunnerToken retrieves a single AGT by ID.
	// Returns metadata only — the token secret is never included.
	//
	// Scope: `runners:read`
	GetRunnerToken(context.Context, *connect.Request[v1.GetRunnerTokenRequest]) (*connect.Response[v1.GetRunnerTokenResponse], error)
	// RevokeRunnerToken permanently revokes an AGT bound to this runner.
	// The agent will receive a 401 on its next request. If this is the only
	// active AGT for the runner, the agent will become disconnected.
	//
	// Scope: `runners:write`
	RevokeRunnerToken(context.Context, *connect.Request[v1.RevokeRunnerTokenRequest]) (*connect.Response[v1.RevokeRunnerTokenResponse], error)
}

// NewRunnerAPIHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRunnerAPIHandler(svc RunnerAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	runnerAPIMethods := v1.File_runner_v1_runner_proto.Services().ByName("RunnerAPI").Methods()
	runnerAPICreateRunnerHandler := connect.NewUnaryHandler(
		RunnerAPICreateRunnerProcedure,
		svc.CreateRunner,
		connect.WithSchema(runnerAPIMethods.ByName("CreateRunner")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIGetRunnerHandler := connect.NewUnaryHandler(
		RunnerAPIGetRunnerProcedure,
		svc.GetRunner,
		connect.WithSchema(runnerAPIMethods.ByName("GetRunner")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIListRunnersHandler := connect.NewUnaryHandler(
		RunnerAPIListRunnersProcedure,
		svc.ListRunners,
		connect.WithSchema(runnerAPIMethods.ByName("ListRunners")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIUpdateRunnerHandler := connect.NewUnaryHandler(
		RunnerAPIUpdateRunnerProcedure,
		svc.UpdateRunner,
		connect.WithSchema(runnerAPIMethods.ByName("UpdateRunner")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIDeleteRunnerHandler := connect.NewUnaryHandler(
		RunnerAPIDeleteRunnerProcedure,
		svc.DeleteRunner,
		connect.WithSchema(runnerAPIMethods.ByName("DeleteRunner")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPICreateRunnerTokenHandler := connect.NewUnaryHandler(
		RunnerAPICreateRunnerTokenProcedure,
		svc.CreateRunnerToken,
		connect.WithSchema(runnerAPIMethods.ByName("CreateRunnerToken")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIListRunnerTokensHandler := connect.NewUnaryHandler(
		RunnerAPIListRunnerTokensProcedure,
		svc.ListRunnerTokens,
		connect.WithSchema(runnerAPIMethods.ByName("ListRunnerTokens")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIGetRunnerTokenHandler := connect.NewUnaryHandler(
		RunnerAPIGetRunnerTokenProcedure,
		svc.GetRunnerToken,
		connect.WithSchema(runnerAPIMethods.ByName("GetRunnerToken")),
		connect.WithHandlerOptions(opts...),
	)
	runnerAPIRevokeRunnerTokenHandler := connect.NewUnaryHandler(
		RunnerAPIRevokeRunnerTokenProcedure,
		svc.RevokeRunnerToken,
		connect.WithSchema(runnerAPIMethods.ByName("RevokeRunnerToken")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.api.runner.v1.RunnerAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RunnerAPICreateRunnerProcedure:
			runnerAPICreateRunnerHandler.ServeHTTP(w, r)
		case RunnerAPIGetRunnerProcedure:
			runnerAPIGetRunnerHandler.ServeHTTP(w, r)
		case RunnerAPIListRunnersProcedure:
			runnerAPIListRunnersHandler.ServeHTTP(w, r)
		case RunnerAPIUpdateRunnerProcedure:
			runnerAPIUpdateRunnerHandler.ServeHTTP(w, r)
		case RunnerAPIDeleteRunnerProcedure:
			runnerAPIDeleteRunnerHandler.ServeHTTP(w, r)
		case RunnerAPICreateRunnerTokenProcedure:
			runnerAPICreateRunnerTokenHandler.ServeHTTP(w, r)
		case RunnerAPIListRunnerTokensProcedure:
			runnerAPIListRunnerTokensHandler.ServeHTTP(w, r)
		case RunnerAPIGetRunnerTokenProcedure:
			runnerAPIGetRunnerTokenHandler.ServeHTTP(w, r)
		case RunnerAPIRevokeRunnerTokenProcedure:
			runnerAPIRevokeRunnerTokenHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRunnerAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedRunnerAPIHandler struct{}

func (UnimplementedRunnerAPIHandler) CreateRunner(context.Context, *connect.Request[v1.CreateRunnerRequest]) (*connect.Response[v1.CreateRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.CreateRunner is not implemented"))
}

func (UnimplementedRunnerAPIHandler) GetRunner(context.Context, *connect.Request[v1.GetRunnerRequest]) (*connect.Response[v1.GetRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.GetRunner is not implemented"))
}

func (UnimplementedRunnerAPIHandler) ListRunners(context.Context, *connect.Request[v1.ListRunnersRequest]) (*connect.Response[v1.ListRunnersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.ListRunners is not implemented"))
}

func (UnimplementedRunnerAPIHandler) UpdateRunner(context.Context, *connect.Request[v1.UpdateRunnerRequest]) (*connect.Response[v1.UpdateRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.UpdateRunner is not implemented"))
}

func (UnimplementedRunnerAPIHandler) DeleteRunner(context.Context, *connect.Request[v1.DeleteRunnerRequest]) (*connect.Response[v1.DeleteRunnerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.DeleteRunner is not implemented"))
}

func (UnimplementedRunnerAPIHandler) CreateRunnerToken(context.Context, *connect.Request[v1.CreateRunnerTokenRequest]) (*connect.Response[v1.CreateRunnerTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.CreateRunnerToken is not implemented"))
}

func (UnimplementedRunnerAPIHandler) ListRunnerTokens(context.Context, *connect.Request[v1.ListRunnerTokensRequest]) (*connect.Response[v1.ListRunnerTokensResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.ListRunnerTokens is not implemented"))
}

func (UnimplementedRunnerAPIHandler) GetRunnerToken(context.Context, *connect.Request[v1.GetRunnerTokenRequest]) (*connect.Response[v1.GetRunnerTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.GetRunnerToken is not implemented"))
}

func (UnimplementedRunnerAPIHandler) RevokeRunnerToken(context.Context, *connect.Request[v1.RevokeRunnerTokenRequest]) (*connect.Response[v1.RevokeRunnerTokenResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.runner.v1.RunnerAPI.RevokeRunnerToken is not implemented"))
}
