// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentAPI_RegisterAgent_FullMethodName = "/admiral.api.agent.v1.AgentAPI/RegisterAgent"
	AgentAPI_GetAgent_FullMethodName      = "/admiral.api.agent.v1.AgentAPI/GetAgent"
	AgentAPI_ListAgents_FullMethodName    = "/admiral.api.agent.v1.AgentAPI/ListAgents"
	AgentAPI_Heartbeat_FullMethodName     = "/admiral.api.agent.v1.AgentAPI/Heartbeat"
)

// AgentAPIClient is the client API for AgentAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AgentAPI manages agent registration, lifecycle, and heartbeat.
//
// Agents are long-lived processes that run in customer environments and connect
// to Admiral's control plane. Each agent is bound to a parent resource — either
// a Cluster or a Runner — and the binding is determined by the Agent Token (AGT)
// used to authenticate.
//
// Agent records are system-managed projections of connection state. Admins can
// observe agents via GetAgent and ListAgents, but cannot create, update, or
// delete them directly. The agent lifecycle is controlled by RegisterAgent
// (creates the record on first boot) and cascading deletes when the parent
// resource (Cluster or Runner) is removed.
type AgentAPIClient interface {
	// RegisterAgent registers a new agent, binding it to its parent resource
	// (Cluster or Runner). The binding is derived from the AGT used to
	// authenticate — the request does not specify which resource to bind to.
	//
	// For Kubernetes agents, the request must include `cluster_uid` (the
	// kube-system namespace UID). This value is written to the Cluster record
	// using a first-write-wins strategy. Subsequent registrations with a
	// different UID return 409 Conflict.
	//
	// Registration is idempotent: if the agent restarts and calls RegisterAgent
	// with the same AGT and matching metadata, the existing agent record is
	// returned and its status is set to ONLINE.
	//
	// Scope: `agents:write` | Token types: `agt`
	RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error)
	// GetAgent retrieves an agent by ID, including its current connectivity
	// status and resource binding.
	//
	// Scope: `agents:read`
	GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error)
	// ListAgents returns a paginated list of agents within the caller's tenant.
	// Use the filter parameter to scope results by resource binding
	// (e.g., `cluster_id = "uuid"` or `runner_id = "uuid"`).
	//
	// Scope: `agents:read`
	ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error)
	// Heartbeat sends a liveness signal from the agent to the control plane.
	// If no heartbeat is received within 3x the poll interval (default 90s),
	// the agent transitions to UNREACHABLE status.
	//
	// Scope: `agents:heartbeat` | Token types: `agt`
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type agentAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentAPIClient(cc grpc.ClientConnInterface) AgentAPIClient {
	return &agentAPIClient{cc}
}

func (c *agentAPIClient) RegisterAgent(ctx context.Context, in *RegisterAgentRequest, opts ...grpc.CallOption) (*RegisterAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterAgentResponse)
	err := c.cc.Invoke(ctx, AgentAPI_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAPIClient) GetAgent(ctx context.Context, in *GetAgentRequest, opts ...grpc.CallOption) (*GetAgentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAgentResponse)
	err := c.cc.Invoke(ctx, AgentAPI_GetAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAPIClient) ListAgents(ctx context.Context, in *ListAgentsRequest, opts ...grpc.CallOption) (*ListAgentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAgentsResponse)
	err := c.cc.Invoke(ctx, AgentAPI_ListAgents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentAPIClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, AgentAPI_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentAPIServer is the server API for AgentAPI service.
// All implementations should embed UnimplementedAgentAPIServer
// for forward compatibility.
//
// AgentAPI manages agent registration, lifecycle, and heartbeat.
//
// Agents are long-lived processes that run in customer environments and connect
// to Admiral's control plane. Each agent is bound to a parent resource — either
// a Cluster or a Runner — and the binding is determined by the Agent Token (AGT)
// used to authenticate.
//
// Agent records are system-managed projections of connection state. Admins can
// observe agents via GetAgent and ListAgents, but cannot create, update, or
// delete them directly. The agent lifecycle is controlled by RegisterAgent
// (creates the record on first boot) and cascading deletes when the parent
// resource (Cluster or Runner) is removed.
type AgentAPIServer interface {
	// RegisterAgent registers a new agent, binding it to its parent resource
	// (Cluster or Runner). The binding is derived from the AGT used to
	// authenticate — the request does not specify which resource to bind to.
	//
	// For Kubernetes agents, the request must include `cluster_uid` (the
	// kube-system namespace UID). This value is written to the Cluster record
	// using a first-write-wins strategy. Subsequent registrations with a
	// different UID return 409 Conflict.
	//
	// Registration is idempotent: if the agent restarts and calls RegisterAgent
	// with the same AGT and matching metadata, the existing agent record is
	// returned and its status is set to ONLINE.
	//
	// Scope: `agents:write` | Token types: `agt`
	RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error)
	// GetAgent retrieves an agent by ID, including its current connectivity
	// status and resource binding.
	//
	// Scope: `agents:read`
	GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error)
	// ListAgents returns a paginated list of agents within the caller's tenant.
	// Use the filter parameter to scope results by resource binding
	// (e.g., `cluster_id = "uuid"` or `runner_id = "uuid"`).
	//
	// Scope: `agents:read`
	ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error)
	// Heartbeat sends a liveness signal from the agent to the control plane.
	// If no heartbeat is received within 3x the poll interval (default 90s),
	// the agent transitions to UNREACHABLE status.
	//
	// Scope: `agents:heartbeat` | Token types: `agt`
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedAgentAPIServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentAPIServer struct{}

func (UnimplementedAgentAPIServer) RegisterAgent(context.Context, *RegisterAgentRequest) (*RegisterAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedAgentAPIServer) GetAgent(context.Context, *GetAgentRequest) (*GetAgentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAgent not implemented")
}
func (UnimplementedAgentAPIServer) ListAgents(context.Context, *ListAgentsRequest) (*ListAgentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAgents not implemented")
}
func (UnimplementedAgentAPIServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedAgentAPIServer) testEmbeddedByValue() {}

// UnsafeAgentAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentAPIServer will
// result in compilation errors.
type UnsafeAgentAPIServer interface {
	mustEmbedUnimplementedAgentAPIServer()
}

func RegisterAgentAPIServer(s grpc.ServiceRegistrar, srv AgentAPIServer) {
	// If the following call panics, it indicates UnimplementedAgentAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentAPI_ServiceDesc, srv)
}

func _AgentAPI_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAPIServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAPI_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAPIServer).RegisterAgent(ctx, req.(*RegisterAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAPI_GetAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAPIServer).GetAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAPI_GetAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAPIServer).GetAgent(ctx, req.(*GetAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAPI_ListAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAPIServer).ListAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAPI_ListAgents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAPIServer).ListAgents(ctx, req.(*ListAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentAPI_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentAPIServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentAPI_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentAPIServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentAPI_ServiceDesc is the grpc.ServiceDesc for AgentAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "admiral.api.agent.v1.AgentAPI",
	HandlerType: (*AgentAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterAgent",
			Handler:    _AgentAPI_RegisterAgent_Handler,
		},
		{
			MethodName: "GetAgent",
			Handler:    _AgentAPI_GetAgent_Handler,
		},
		{
			MethodName: "ListAgents",
			Handler:    _AgentAPI_ListAgents_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _AgentAPI_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent/v1/agent.proto",
}
