// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/v1/agent.proto

package agentv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "go.admiral.io/sdk/proto/authz/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AgentStatus represents the connectivity state of an agent.
type AgentStatus int32

const (
	// Default value. Must not be used.
	AgentStatus_AGENT_STATUS_UNSPECIFIED AgentStatus = 0
	// The agent is connected and sending heartbeats.
	AgentStatus_AGENT_STATUS_ONLINE AgentStatus = 1
	// The agent has gracefully disconnected.
	AgentStatus_AGENT_STATUS_OFFLINE AgentStatus = 2
	// No heartbeat received within 3x the poll interval.
	AgentStatus_AGENT_STATUS_UNREACHABLE AgentStatus = 3
)

// Enum value maps for AgentStatus.
var (
	AgentStatus_name = map[int32]string{
		0: "AGENT_STATUS_UNSPECIFIED",
		1: "AGENT_STATUS_ONLINE",
		2: "AGENT_STATUS_OFFLINE",
		3: "AGENT_STATUS_UNREACHABLE",
	}
	AgentStatus_value = map[string]int32{
		"AGENT_STATUS_UNSPECIFIED": 0,
		"AGENT_STATUS_ONLINE":      1,
		"AGENT_STATUS_OFFLINE":     2,
		"AGENT_STATUS_UNREACHABLE": 3,
	}
)

func (x AgentStatus) Enum() *AgentStatus {
	p := new(AgentStatus)
	*p = x
	return p
}

func (x AgentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AgentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_v1_agent_proto_enumTypes[0].Descriptor()
}

func (AgentStatus) Type() protoreflect.EnumType {
	return &file_agent_v1_agent_proto_enumTypes[0]
}

func (x AgentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AgentStatus.Descriptor instead.
func (AgentStatus) EnumDescriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

// KubernetesAgentMetadata contains registration-time metadata for a Kubernetes
// cluster agent. This is sent once during RegisterAgent, not on every heartbeat.
// Dynamic telemetry (k8s version, node count, etc.) is reported separately via
// ClusterAPI.ReportClusterStatus.
type KubernetesAgentMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The UID of the kube-system namespace, used as a stable physical cluster
	// identifier. Written to the Cluster record on first registration using a
	// first-write-wins strategy. If a subsequent registration presents a
	// different UID, the server returns 409 Conflict.
	ClusterUid    string `protobuf:"bytes,1,opt,name=cluster_uid,json=clusterUid,proto3" json:"cluster_uid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KubernetesAgentMetadata) Reset() {
	*x = KubernetesAgentMetadata{}
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KubernetesAgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesAgentMetadata) ProtoMessage() {}

func (x *KubernetesAgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesAgentMetadata.ProtoReflect.Descriptor instead.
func (*KubernetesAgentMetadata) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesAgentMetadata) GetClusterUid() string {
	if x != nil {
		return x.ClusterUid
	}
	return ""
}

// RunnerAgentMetadata contains registration-time metadata for a runner agent.
// Currently empty — runner configuration is managed on the Runner resource by
// admins, not self-reported by the agent at registration.
type RunnerAgentMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunnerAgentMetadata) Reset() {
	*x = RunnerAgentMetadata{}
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunnerAgentMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunnerAgentMetadata) ProtoMessage() {}

func (x *RunnerAgentMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunnerAgentMetadata.ProtoReflect.Descriptor instead.
func (*RunnerAgentMetadata) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{1}
}

// Agent represents a registered agent process connected to Admiral's control
// plane. Each agent is bound to exactly one parent resource (Cluster or Runner)
// and tracks the connection state of the deployed agent binary.
//
// Agent records are system-managed — they are created by RegisterAgent and
// deleted when the parent resource is removed. Admins observe agents via
// GetAgent and ListAgents but do not create, update, or delete them directly.
type Agent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the agent (UUID).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Tenant this agent belongs to (UUID).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// The cluster this agent is bound to (UUID). Set for Kubernetes agents.
	// Mutually exclusive with runner_id.
	ClusterId string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	// The runner this agent is bound to (UUID). Set for runner agents.
	// Mutually exclusive with cluster_id.
	RunnerId string `protobuf:"bytes,4,opt,name=runner_id,json=runnerId,proto3" json:"runner_id,omitempty"`
	// Human-readable name for the agent (e.g., "prod-us-east-1-agent").
	DisplayName string `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Agent software version (e.g., "0.1.0").
	Version string `protobuf:"bytes,6,opt,name=version,proto3" json:"version,omitempty"`
	// Current connectivity status.
	Status AgentStatus `protobuf:"varint,7,opt,name=status,proto3,enum=admiral.api.agent.v1.AgentStatus" json:"status,omitempty"`
	// When the agent last sent a heartbeat.
	LastHeartbeatAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_heartbeat_at,json=lastHeartbeatAt,proto3" json:"last_heartbeat_at,omitempty"`
	// When the agent was registered.
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// When the agent record was last updated.
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Agent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Agent) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Agent) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Agent) GetRunnerId() string {
	if x != nil {
		return x.RunnerId
	}
	return ""
}

func (x *Agent) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *Agent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Agent) GetStatus() AgentStatus {
	if x != nil {
		return x.Status
	}
	return AgentStatus_AGENT_STATUS_UNSPECIFIED
}

func (x *Agent) GetLastHeartbeatAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastHeartbeatAt
	}
	return nil
}

func (x *Agent) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Agent) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// RegisterAgentRequest contains the parameters for registering a new agent.
// The parent resource binding (Cluster or Runner) is derived from the AGT
// used to authenticate — it does not need to be specified in the request.
type RegisterAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable name for the agent.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Agent software version (e.g., "0.1.0").
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Agent-type-specific registration metadata. The server validates that the
	// metadata variant matches the AGT's resource binding (e.g., a cluster-bound
	// AGT must provide KubernetesAgentMetadata).
	//
	// Types that are valid to be assigned to Metadata:
	//
	//	*RegisterAgentRequest_Kubernetes
	//	*RegisterAgentRequest_Runner
	Metadata      isRegisterAgentRequest_Metadata `protobuf_oneof:"metadata"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAgentRequest) Reset() {
	*x = RegisterAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentRequest) ProtoMessage() {}

func (x *RegisterAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentRequest.ProtoReflect.Descriptor instead.
func (*RegisterAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterAgentRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterAgentRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterAgentRequest) GetMetadata() isRegisterAgentRequest_Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterAgentRequest) GetKubernetes() *KubernetesAgentMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*RegisterAgentRequest_Kubernetes); ok {
			return x.Kubernetes
		}
	}
	return nil
}

func (x *RegisterAgentRequest) GetRunner() *RunnerAgentMetadata {
	if x != nil {
		if x, ok := x.Metadata.(*RegisterAgentRequest_Runner); ok {
			return x.Runner
		}
	}
	return nil
}

type isRegisterAgentRequest_Metadata interface {
	isRegisterAgentRequest_Metadata()
}

type RegisterAgentRequest_Kubernetes struct {
	// Registration metadata for Kubernetes cluster agents. Required when the
	// AGT is bound to a Cluster.
	Kubernetes *KubernetesAgentMetadata `protobuf:"bytes,3,opt,name=kubernetes,proto3,oneof"`
}

type RegisterAgentRequest_Runner struct {
	// Registration metadata for runner agents. Required when the AGT is
	// bound to a Runner.
	Runner *RunnerAgentMetadata `protobuf:"bytes,4,opt,name=runner,proto3,oneof"`
}

func (*RegisterAgentRequest_Kubernetes) isRegisterAgentRequest_Metadata() {}

func (*RegisterAgentRequest_Runner) isRegisterAgentRequest_Metadata() {}

// RegisterAgentResponse contains the registered agent and server-controlled
// configuration for the agent's polling behavior.
type RegisterAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The registered agent. On first registration, a new record is created with
	// status ONLINE. On re-registration (agent restart), the existing record is
	// returned with status set to ONLINE.
	Agent *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// Server-controlled heartbeat interval in seconds. The agent should send
	// heartbeats at this frequency. If no heartbeat is received within 3x this
	// interval, the agent transitions to UNREACHABLE.
	PollIntervalSeconds int32 `protobuf:"varint,2,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	// Server-controlled status push interval in seconds. For Kubernetes agents,
	// this controls how often to push cluster telemetry via ReportClusterStatus.
	StatusPushIntervalSeconds int32 `protobuf:"varint,3,opt,name=status_push_interval_seconds,json=statusPushIntervalSeconds,proto3" json:"status_push_interval_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegisterAgentResponse) Reset() {
	*x = RegisterAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAgentResponse) ProtoMessage() {}

func (x *RegisterAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAgentResponse.ProtoReflect.Descriptor instead.
func (*RegisterAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *RegisterAgentResponse) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *RegisterAgentResponse) GetStatusPushIntervalSeconds() int32 {
	if x != nil {
		return x.StatusPushIntervalSeconds
	}
	return 0
}

// GetAgentRequest identifies an agent to retrieve.
type GetAgentRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The unique identifier of the agent (UUID).
	AgentId       string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentRequest) Reset() {
	*x = GetAgentRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentRequest) ProtoMessage() {}

func (x *GetAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentRequest.ProtoReflect.Descriptor instead.
func (*GetAgentRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetAgentRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

// GetAgentResponse contains the requested agent.
type GetAgentResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent.
	Agent         *Agent `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAgentResponse) Reset() {
	*x = GetAgentResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAgentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAgentResponse) ProtoMessage() {}

func (x *GetAgentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAgentResponse.ProtoReflect.Descriptor instead.
func (*GetAgentResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *GetAgentResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

// ListAgentsRequest contains pagination and filter parameters.
type ListAgentsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Maximum number of agents to return per page.
	PageSize int32 `protobuf:"varint,1,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// Opaque pagination token from a previous response.
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Filter expression using the PEG filter DSL. Supported fields include
	// `cluster_id`, `runner_id`, and `status`.
	// Examples: `cluster_id = "uuid"`, `runner_id = "uuid"`, `status = "ONLINE"`.
	Filter        string `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ListAgentsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListAgentsRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListAgentsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// ListAgentsResponse contains a page of agents.
type ListAgentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of agents.
	Agents []*Agent `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	// Pagination token for the next page. Empty when there are no more results.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ListAgentsResponse) GetAgents() []*Agent {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ListAgentsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// HeartbeatRequest contains a liveness signal from the agent.
type HeartbeatRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The agent sending the heartbeat (UUID).
	AgentId string `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Current agent software version.
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// How long the agent process has been running, in seconds.
	UptimeSeconds int64 `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HeartbeatRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *HeartbeatRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HeartbeatRequest) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// HeartbeatResponse acknowledges the heartbeat and provides server-controlled
// configuration for the agent's polling behavior.
type HeartbeatResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the heartbeat was accepted.
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	// Server-controlled heartbeat interval in seconds. The agent should use
	// this value for its next heartbeat cycle. Allows the server to dynamically
	// adjust frequency (e.g., faster when changes are pending).
	PollIntervalSeconds int32 `protobuf:"varint,2,opt,name=poll_interval_seconds,json=pollIntervalSeconds,proto3" json:"poll_interval_seconds,omitempty"`
	// Server-controlled status push interval in seconds.
	StatusPushIntervalSeconds int32 `protobuf:"varint,3,opt,name=status_push_interval_seconds,json=statusPushIntervalSeconds,proto3" json:"status_push_interval_seconds,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_agent_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HeartbeatResponse) GetPollIntervalSeconds() int32 {
	if x != nil {
		return x.PollIntervalSeconds
	}
	return 0
}

func (x *HeartbeatResponse) GetStatusPushIntervalSeconds() int32 {
	if x != nil {
		return x.StatusPushIntervalSeconds
	}
	return 0
}

var File_agent_v1_agent_proto protoreflect.FileDescriptor

const file_agent_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14agent/v1/agent.proto\x12\x14admiral.api.agent.v1\x1a\x1aauthz/v1/annotations.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x17KubernetesAgentMetadata\x12(\n" +
	"\vcluster_uid\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"clusterUid\"\x15\n" +
	"\x13RunnerAgentMetadata\"\xc6\x03\n" +
	"\x05Agent\x12\x18\n" +
	"\x02id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02id\x12%\n" +
	"\ttenant_id\x18\x02 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12\x1b\n" +
	"\trunner_id\x18\x04 \x01(\tR\brunnerId\x12-\n" +
	"\fdisplay_name\x18\x05 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12\x18\n" +
	"\aversion\x18\x06 \x01(\tR\aversion\x129\n" +
	"\x06status\x18\a \x01(\x0e2!.admiral.api.agent.v1.AgentStatusR\x06status\x12F\n" +
	"\x11last_heartbeat_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0flastHeartbeatAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x81\x02\n" +
	"\x14RegisterAgentRequest\x12-\n" +
	"\fdisplay_name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xff\x01R\vdisplayName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12O\n" +
	"\n" +
	"kubernetes\x18\x03 \x01(\v2-.admiral.api.agent.v1.KubernetesAgentMetadataH\x00R\n" +
	"kubernetes\x12C\n" +
	"\x06runner\x18\x04 \x01(\v2).admiral.api.agent.v1.RunnerAgentMetadataH\x00R\x06runnerB\n" +
	"\n" +
	"\bmetadata\"\xbf\x01\n" +
	"\x15RegisterAgentResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x1b.admiral.api.agent.v1.AgentR\x05agent\x122\n" +
	"\x15poll_interval_seconds\x18\x02 \x01(\x05R\x13pollIntervalSeconds\x12?\n" +
	"\x1cstatus_push_interval_seconds\x18\x03 \x01(\x05R\x19statusPushIntervalSeconds\"6\n" +
	"\x0fGetAgentRequest\x12#\n" +
	"\bagent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aagentId\"E\n" +
	"\x10GetAgentResponse\x121\n" +
	"\x05agent\x18\x01 \x01(\v2\x1b.admiral.api.agent.v1.AgentR\x05agent\"g\n" +
	"\x11ListAgentsRequest\x12\x1b\n" +
	"\tpage_size\x18\x01 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x02 \x01(\tR\tpageToken\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\"q\n" +
	"\x12ListAgentsResponse\x123\n" +
	"\x06agents\x18\x01 \x03(\v2\x1b.admiral.api.agent.v1.AgentR\x06agents\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"x\n" +
	"\x10HeartbeatRequest\x12#\n" +
	"\bagent_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\aagentId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"\x98\x01\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x122\n" +
	"\x15poll_interval_seconds\x18\x02 \x01(\x05R\x13pollIntervalSeconds\x12?\n" +
	"\x1cstatus_push_interval_seconds\x18\x03 \x01(\x05R\x19statusPushIntervalSeconds*|\n" +
	"\vAgentStatus\x12\x1c\n" +
	"\x18AGENT_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13AGENT_STATUS_ONLINE\x10\x01\x12\x18\n" +
	"\x14AGENT_STATUS_OFFLINE\x10\x02\x12\x1c\n" +
	"\x18AGENT_STATUS_UNREACHABLE\x10\x032\xe5\x04\n" +
	"\bAgentAPI\x12\x9f\x01\n" +
	"\rRegisterAgent\x12*.admiral.api.agent.v1.RegisterAgentRequest\x1a+.admiral.api.agent.v1.RegisterAgentResponse\"5\x82\xb5\x18\x13\n" +
	"\fagents:write\x12\x03agt\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/v1/agents:register\x12\x89\x01\n" +
	"\bGetAgent\x12%.admiral.api.agent.v1.GetAgentRequest\x1a&.admiral.api.agent.v1.GetAgentResponse\".\x82\xb5\x18\r\n" +
	"\vagents:read\x82\xd3\xe4\x93\x02\x17\x12\x15/v1/agents/{agent_id}\x12\x84\x01\n" +
	"\n" +
	"ListAgents\x12'.admiral.api.agent.v1.ListAgentsRequest\x1a(.admiral.api.agent.v1.ListAgentsResponse\"#\x82\xb5\x18\r\n" +
	"\vagents:read\x82\xd3\xe4\x93\x02\f\x12\n" +
	"/v1/agents\x12\xa3\x01\n" +
	"\tHeartbeat\x12&.admiral.api.agent.v1.HeartbeatRequest\x1a'.admiral.api.agent.v1.HeartbeatResponse\"E\x82\xb5\x18\x17\n" +
	"\x10agents:heartbeat\x12\x03agt\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/v1/agents/{agent_id}/heartbeatB\xc3\x01\n" +
	"\x18com.admiral.api.agent.v1B\n" +
	"AgentProtoP\x01Z(go.admiral.io/sdk/proto/agent/v1;agentv1\xa2\x02\x03AAA\xaa\x02\x14Admiral.Api.Agent.V1\xca\x02\x14Admiral\\Api\\Agent\\V1\xe2\x02 Admiral\\Api\\Agent\\V1\\GPBMetadata\xea\x02\x17Admiral::Api::Agent::V1b\x06proto3"

var (
	file_agent_v1_agent_proto_rawDescOnce sync.Once
	file_agent_v1_agent_proto_rawDescData []byte
)

func file_agent_v1_agent_proto_rawDescGZIP() []byte {
	file_agent_v1_agent_proto_rawDescOnce.Do(func() {
		file_agent_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)))
	})
	return file_agent_v1_agent_proto_rawDescData
}

var file_agent_v1_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_agent_v1_agent_proto_goTypes = []any{
	(AgentStatus)(0),                // 0: admiral.api.agent.v1.AgentStatus
	(*KubernetesAgentMetadata)(nil), // 1: admiral.api.agent.v1.KubernetesAgentMetadata
	(*RunnerAgentMetadata)(nil),     // 2: admiral.api.agent.v1.RunnerAgentMetadata
	(*Agent)(nil),                   // 3: admiral.api.agent.v1.Agent
	(*RegisterAgentRequest)(nil),    // 4: admiral.api.agent.v1.RegisterAgentRequest
	(*RegisterAgentResponse)(nil),   // 5: admiral.api.agent.v1.RegisterAgentResponse
	(*GetAgentRequest)(nil),         // 6: admiral.api.agent.v1.GetAgentRequest
	(*GetAgentResponse)(nil),        // 7: admiral.api.agent.v1.GetAgentResponse
	(*ListAgentsRequest)(nil),       // 8: admiral.api.agent.v1.ListAgentsRequest
	(*ListAgentsResponse)(nil),      // 9: admiral.api.agent.v1.ListAgentsResponse
	(*HeartbeatRequest)(nil),        // 10: admiral.api.agent.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),       // 11: admiral.api.agent.v1.HeartbeatResponse
	(*timestamppb.Timestamp)(nil),   // 12: google.protobuf.Timestamp
}
var file_agent_v1_agent_proto_depIdxs = []int32{
	0,  // 0: admiral.api.agent.v1.Agent.status:type_name -> admiral.api.agent.v1.AgentStatus
	12, // 1: admiral.api.agent.v1.Agent.last_heartbeat_at:type_name -> google.protobuf.Timestamp
	12, // 2: admiral.api.agent.v1.Agent.created_at:type_name -> google.protobuf.Timestamp
	12, // 3: admiral.api.agent.v1.Agent.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 4: admiral.api.agent.v1.RegisterAgentRequest.kubernetes:type_name -> admiral.api.agent.v1.KubernetesAgentMetadata
	2,  // 5: admiral.api.agent.v1.RegisterAgentRequest.runner:type_name -> admiral.api.agent.v1.RunnerAgentMetadata
	3,  // 6: admiral.api.agent.v1.RegisterAgentResponse.agent:type_name -> admiral.api.agent.v1.Agent
	3,  // 7: admiral.api.agent.v1.GetAgentResponse.agent:type_name -> admiral.api.agent.v1.Agent
	3,  // 8: admiral.api.agent.v1.ListAgentsResponse.agents:type_name -> admiral.api.agent.v1.Agent
	4,  // 9: admiral.api.agent.v1.AgentAPI.RegisterAgent:input_type -> admiral.api.agent.v1.RegisterAgentRequest
	6,  // 10: admiral.api.agent.v1.AgentAPI.GetAgent:input_type -> admiral.api.agent.v1.GetAgentRequest
	8,  // 11: admiral.api.agent.v1.AgentAPI.ListAgents:input_type -> admiral.api.agent.v1.ListAgentsRequest
	10, // 12: admiral.api.agent.v1.AgentAPI.Heartbeat:input_type -> admiral.api.agent.v1.HeartbeatRequest
	5,  // 13: admiral.api.agent.v1.AgentAPI.RegisterAgent:output_type -> admiral.api.agent.v1.RegisterAgentResponse
	7,  // 14: admiral.api.agent.v1.AgentAPI.GetAgent:output_type -> admiral.api.agent.v1.GetAgentResponse
	9,  // 15: admiral.api.agent.v1.AgentAPI.ListAgents:output_type -> admiral.api.agent.v1.ListAgentsResponse
	11, // 16: admiral.api.agent.v1.AgentAPI.Heartbeat:output_type -> admiral.api.agent.v1.HeartbeatResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_agent_v1_agent_proto_init() }
func file_agent_v1_agent_proto_init() {
	if File_agent_v1_agent_proto != nil {
		return
	}
	file_agent_v1_agent_proto_msgTypes[3].OneofWrappers = []any{
		(*RegisterAgentRequest_Kubernetes)(nil),
		(*RegisterAgentRequest_Runner)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_v1_agent_proto_rawDesc), len(file_agent_v1_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_v1_agent_proto_goTypes,
		DependencyIndexes: file_agent_v1_agent_proto_depIdxs,
		EnumInfos:         file_agent_v1_agent_proto_enumTypes,
		MessageInfos:      file_agent_v1_agent_proto_msgTypes,
	}.Build()
	File_agent_v1_agent_proto = out.File
	file_agent_v1_agent_proto_goTypes = nil
	file_agent_v1_agent_proto_depIdxs = nil
}
