// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: agent/v1/agent.proto

package agentv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on KubernetesAgentMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *KubernetesAgentMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on KubernetesAgentMetadata with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// KubernetesAgentMetadataMultiError, or nil if none found.
func (m *KubernetesAgentMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *KubernetesAgentMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for ClusterUid

	if len(errors) > 0 {
		return KubernetesAgentMetadataMultiError(errors)
	}

	return nil
}

// KubernetesAgentMetadataMultiError is an error wrapping multiple validation
// errors returned by KubernetesAgentMetadata.ValidateAll() if the designated
// constraints aren't met.
type KubernetesAgentMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m KubernetesAgentMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m KubernetesAgentMetadataMultiError) AllErrors() []error { return m }

// KubernetesAgentMetadataValidationError is the validation error returned by
// KubernetesAgentMetadata.Validate if the designated constraints aren't met.
type KubernetesAgentMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e KubernetesAgentMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e KubernetesAgentMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e KubernetesAgentMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e KubernetesAgentMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e KubernetesAgentMetadataValidationError) ErrorName() string {
	return "KubernetesAgentMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e KubernetesAgentMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sKubernetesAgentMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = KubernetesAgentMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = KubernetesAgentMetadataValidationError{}

// Validate checks the field values on RunnerAgentMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RunnerAgentMetadata) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RunnerAgentMetadata with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RunnerAgentMetadataMultiError, or nil if none found.
func (m *RunnerAgentMetadata) ValidateAll() error {
	return m.validate(true)
}

func (m *RunnerAgentMetadata) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RunnerAgentMetadataMultiError(errors)
	}

	return nil
}

// RunnerAgentMetadataMultiError is an error wrapping multiple validation
// errors returned by RunnerAgentMetadata.ValidateAll() if the designated
// constraints aren't met.
type RunnerAgentMetadataMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunnerAgentMetadataMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunnerAgentMetadataMultiError) AllErrors() []error { return m }

// RunnerAgentMetadataValidationError is the validation error returned by
// RunnerAgentMetadata.Validate if the designated constraints aren't met.
type RunnerAgentMetadataValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunnerAgentMetadataValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunnerAgentMetadataValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunnerAgentMetadataValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunnerAgentMetadataValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunnerAgentMetadataValidationError) ErrorName() string {
	return "RunnerAgentMetadataValidationError"
}

// Error satisfies the builtin error interface
func (e RunnerAgentMetadataValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunnerAgentMetadata.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunnerAgentMetadataValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunnerAgentMetadataValidationError{}

// Validate checks the field values on Agent with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Agent) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Agent with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AgentMultiError, or nil if none found.
func (m *Agent) ValidateAll() error {
	return m.validate(true)
}

func (m *Agent) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for ClusterId

	// no validation rules for RunnerId

	// no validation rules for DisplayName

	// no validation rules for Version

	// no validation rules for Status

	if all {
		switch v := interface{}(m.GetLastHeartbeatAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "LastHeartbeatAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "LastHeartbeatAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLastHeartbeatAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgentValidationError{
				field:  "LastHeartbeatAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgentValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AgentValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AgentValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AgentMultiError(errors)
	}

	return nil
}

// AgentMultiError is an error wrapping multiple validation errors returned by
// Agent.ValidateAll() if the designated constraints aren't met.
type AgentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AgentMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AgentMultiError) AllErrors() []error { return m }

// AgentValidationError is the validation error returned by Agent.Validate if
// the designated constraints aren't met.
type AgentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AgentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AgentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AgentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AgentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AgentValidationError) ErrorName() string { return "AgentValidationError" }

// Error satisfies the builtin error interface
func (e AgentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAgent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AgentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AgentValidationError{}

// Validate checks the field values on RegisterAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterAgentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterAgentRequestMultiError, or nil if none found.
func (m *RegisterAgentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterAgentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	// no validation rules for Version

	switch v := m.Metadata.(type) {
	case *RegisterAgentRequest_Kubernetes:
		if v == nil {
			err := RegisterAgentRequestValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetKubernetes()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RegisterAgentRequestValidationError{
						field:  "Kubernetes",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RegisterAgentRequestValidationError{
						field:  "Kubernetes",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetKubernetes()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RegisterAgentRequestValidationError{
					field:  "Kubernetes",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *RegisterAgentRequest_Runner:
		if v == nil {
			err := RegisterAgentRequestValidationError{
				field:  "Metadata",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetRunner()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, RegisterAgentRequestValidationError{
						field:  "Runner",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, RegisterAgentRequestValidationError{
						field:  "Runner",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetRunner()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return RegisterAgentRequestValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return RegisterAgentRequestMultiError(errors)
	}

	return nil
}

// RegisterAgentRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterAgentRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterAgentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterAgentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterAgentRequestMultiError) AllErrors() []error { return m }

// RegisterAgentRequestValidationError is the validation error returned by
// RegisterAgentRequest.Validate if the designated constraints aren't met.
type RegisterAgentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAgentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAgentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAgentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAgentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAgentRequestValidationError) ErrorName() string {
	return "RegisterAgentRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAgentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAgentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAgentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAgentRequestValidationError{}

// Validate checks the field values on RegisterAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterAgentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterAgentResponseMultiError, or nil if none found.
func (m *RegisterAgentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterAgentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAgent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RegisterAgentResponseValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RegisterAgentResponseValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAgent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RegisterAgentResponseValidationError{
				field:  "Agent",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PollIntervalSeconds

	// no validation rules for StatusPushIntervalSeconds

	if len(errors) > 0 {
		return RegisterAgentResponseMultiError(errors)
	}

	return nil
}

// RegisterAgentResponseMultiError is an error wrapping multiple validation
// errors returned by RegisterAgentResponse.ValidateAll() if the designated
// constraints aren't met.
type RegisterAgentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterAgentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterAgentResponseMultiError) AllErrors() []error { return m }

// RegisterAgentResponseValidationError is the validation error returned by
// RegisterAgentResponse.Validate if the designated constraints aren't met.
type RegisterAgentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAgentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAgentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAgentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAgentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAgentResponseValidationError) ErrorName() string {
	return "RegisterAgentResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAgentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAgentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAgentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAgentResponseValidationError{}

// Validate checks the field values on GetAgentRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAgentRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAgentRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAgentRequestMultiError, or nil if none found.
func (m *GetAgentRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAgentRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	if len(errors) > 0 {
		return GetAgentRequestMultiError(errors)
	}

	return nil
}

// GetAgentRequestMultiError is an error wrapping multiple validation errors
// returned by GetAgentRequest.ValidateAll() if the designated constraints
// aren't met.
type GetAgentRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAgentRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAgentRequestMultiError) AllErrors() []error { return m }

// GetAgentRequestValidationError is the validation error returned by
// GetAgentRequest.Validate if the designated constraints aren't met.
type GetAgentRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAgentRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAgentRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAgentRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAgentRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAgentRequestValidationError) ErrorName() string { return "GetAgentRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetAgentRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAgentRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAgentRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAgentRequestValidationError{}

// Validate checks the field values on GetAgentResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetAgentResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetAgentResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetAgentResponseMultiError, or nil if none found.
func (m *GetAgentResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetAgentResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAgent()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetAgentResponseValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetAgentResponseValidationError{
					field:  "Agent",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAgent()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetAgentResponseValidationError{
				field:  "Agent",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetAgentResponseMultiError(errors)
	}

	return nil
}

// GetAgentResponseMultiError is an error wrapping multiple validation errors
// returned by GetAgentResponse.ValidateAll() if the designated constraints
// aren't met.
type GetAgentResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetAgentResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetAgentResponseMultiError) AllErrors() []error { return m }

// GetAgentResponseValidationError is the validation error returned by
// GetAgentResponse.Validate if the designated constraints aren't met.
type GetAgentResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetAgentResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetAgentResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetAgentResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetAgentResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetAgentResponseValidationError) ErrorName() string { return "GetAgentResponseValidationError" }

// Error satisfies the builtin error interface
func (e GetAgentResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetAgentResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetAgentResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetAgentResponseValidationError{}

// Validate checks the field values on ListAgentsRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *ListAgentsRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAgentsRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAgentsRequestMultiError, or nil if none found.
func (m *ListAgentsRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAgentsRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for Filter

	if len(errors) > 0 {
		return ListAgentsRequestMultiError(errors)
	}

	return nil
}

// ListAgentsRequestMultiError is an error wrapping multiple validation errors
// returned by ListAgentsRequest.ValidateAll() if the designated constraints
// aren't met.
type ListAgentsRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAgentsRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAgentsRequestMultiError) AllErrors() []error { return m }

// ListAgentsRequestValidationError is the validation error returned by
// ListAgentsRequest.Validate if the designated constraints aren't met.
type ListAgentsRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentsRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentsRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentsRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentsRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentsRequestValidationError) ErrorName() string {
	return "ListAgentsRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentsRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentsRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentsRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentsRequestValidationError{}

// Validate checks the field values on ListAgentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListAgentsResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListAgentsResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListAgentsResponseMultiError, or nil if none found.
func (m *ListAgentsResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListAgentsResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAgents() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListAgentsResponseValidationError{
						field:  fmt.Sprintf("Agents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListAgentsResponseValidationError{
						field:  fmt.Sprintf("Agents[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListAgentsResponseValidationError{
					field:  fmt.Sprintf("Agents[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListAgentsResponseMultiError(errors)
	}

	return nil
}

// ListAgentsResponseMultiError is an error wrapping multiple validation errors
// returned by ListAgentsResponse.ValidateAll() if the designated constraints
// aren't met.
type ListAgentsResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListAgentsResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListAgentsResponseMultiError) AllErrors() []error { return m }

// ListAgentsResponseValidationError is the validation error returned by
// ListAgentsResponse.Validate if the designated constraints aren't met.
type ListAgentsResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListAgentsResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListAgentsResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListAgentsResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListAgentsResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListAgentsResponseValidationError) ErrorName() string {
	return "ListAgentsResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListAgentsResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListAgentsResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListAgentsResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListAgentsResponseValidationError{}

// Validate checks the field values on HeartbeatRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HeartbeatRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeartbeatRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeartbeatRequestMultiError, or nil if none found.
func (m *HeartbeatRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *HeartbeatRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AgentId

	// no validation rules for Version

	// no validation rules for UptimeSeconds

	if len(errors) > 0 {
		return HeartbeatRequestMultiError(errors)
	}

	return nil
}

// HeartbeatRequestMultiError is an error wrapping multiple validation errors
// returned by HeartbeatRequest.ValidateAll() if the designated constraints
// aren't met.
type HeartbeatRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeartbeatRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeartbeatRequestMultiError) AllErrors() []error { return m }

// HeartbeatRequestValidationError is the validation error returned by
// HeartbeatRequest.Validate if the designated constraints aren't met.
type HeartbeatRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeartbeatRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeartbeatRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeartbeatRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeartbeatRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeartbeatRequestValidationError) ErrorName() string { return "HeartbeatRequestValidationError" }

// Error satisfies the builtin error interface
func (e HeartbeatRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeartbeatRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeartbeatRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeartbeatRequestValidationError{}

// Validate checks the field values on HeartbeatResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *HeartbeatResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on HeartbeatResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// HeartbeatResponseMultiError, or nil if none found.
func (m *HeartbeatResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *HeartbeatResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ok

	// no validation rules for PollIntervalSeconds

	// no validation rules for StatusPushIntervalSeconds

	if len(errors) > 0 {
		return HeartbeatResponseMultiError(errors)
	}

	return nil
}

// HeartbeatResponseMultiError is an error wrapping multiple validation errors
// returned by HeartbeatResponse.ValidateAll() if the designated constraints
// aren't met.
type HeartbeatResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m HeartbeatResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m HeartbeatResponseMultiError) AllErrors() []error { return m }

// HeartbeatResponseValidationError is the validation error returned by
// HeartbeatResponse.Validate if the designated constraints aren't met.
type HeartbeatResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e HeartbeatResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e HeartbeatResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e HeartbeatResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e HeartbeatResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e HeartbeatResponseValidationError) ErrorName() string {
	return "HeartbeatResponseValidationError"
}

// Error satisfies the builtin error interface
func (e HeartbeatResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sHeartbeatResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = HeartbeatResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = HeartbeatResponseValidationError{}
