// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openapi.proto

package protov1

import (
	_ "github.com/google/gnostic/openapiv3"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_openapi_proto protoreflect.FileDescriptor

const file_openapi_proto_rawDesc = "" +
	"\n" +
	"\ropenapi.proto\x12\x0eadmiral.api.v1\x1a$gnostic/openapi/v3/annotations.protoB\xc6\x01\xbaG#\x12!\n" +
	"\vAdmiral API\x12\vAdmiral API2\x050.0.0\n" +
	"\x12com.admiral.api.v1B\fOpenapiProtoP\x01Z\"go.admiral.io/sdk/proto/v1;protov1\xa2\x02\x03AAX\xaa\x02\x0eAdmiral.Api.V1\xca\x02\x0eAdmiral\\Api\\V1\xe2\x02\x1aAdmiral\\Api\\V1\\GPBMetadata\xea\x02\x10Admiral::Api::V1b\x06proto3"

var file_openapi_proto_goTypes = []any{}
var file_openapi_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openapi_proto_init() }
func file_openapi_proto_init() {
	if File_openapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openapi_proto_rawDesc), len(file_openapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openapi_proto_goTypes,
		DependencyIndexes: file_openapi_proto_depIdxs,
	}.Build()
	File_openapi_proto = out.File
	file_openapi_proto_goTypes = nil
	file_openapi_proto_depIdxs = nil
}
