// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: agent/v1/agent.proto

package agentv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "go.admiral.io/sdk/proto/agent/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AgentAPIName is the fully-qualified name of the AgentAPI service.
	AgentAPIName = "admiral.api.agent.v1.AgentAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AgentAPIRegisterAgentProcedure is the fully-qualified name of the AgentAPI's RegisterAgent RPC.
	AgentAPIRegisterAgentProcedure = "/admiral.api.agent.v1.AgentAPI/RegisterAgent"
	// AgentAPIGetAgentProcedure is the fully-qualified name of the AgentAPI's GetAgent RPC.
	AgentAPIGetAgentProcedure = "/admiral.api.agent.v1.AgentAPI/GetAgent"
	// AgentAPIListAgentsProcedure is the fully-qualified name of the AgentAPI's ListAgents RPC.
	AgentAPIListAgentsProcedure = "/admiral.api.agent.v1.AgentAPI/ListAgents"
	// AgentAPIHeartbeatProcedure is the fully-qualified name of the AgentAPI's Heartbeat RPC.
	AgentAPIHeartbeatProcedure = "/admiral.api.agent.v1.AgentAPI/Heartbeat"
)

// AgentAPIClient is a client for the admiral.api.agent.v1.AgentAPI service.
type AgentAPIClient interface {
	// RegisterAgent registers a new agent, binding it to its parent resource
	// (Cluster or Runner). The binding is derived from the AGT used to
	// authenticate — the request does not specify which resource to bind to.
	//
	// For Kubernetes agents, the request must include `cluster_uid` (the
	// kube-system namespace UID). This value is written to the Cluster record
	// using a first-write-wins strategy. Subsequent registrations with a
	// different UID return 409 Conflict.
	//
	// Registration is idempotent: if the agent restarts and calls RegisterAgent
	// with the same AGT and matching metadata, the existing agent record is
	// returned and its status is set to ONLINE.
	//
	// Scope: `agents:write` | Token types: `agt`
	RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error)
	// GetAgent retrieves an agent by ID, including its current connectivity
	// status and resource binding.
	//
	// Scope: `agents:read`
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// ListAgents returns a paginated list of agents within the caller's tenant.
	// Use the filter parameter to scope results by resource binding
	// (e.g., `cluster_id = "uuid"` or `runner_id = "uuid"`).
	//
	// Scope: `agents:read`
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Heartbeat sends a liveness signal from the agent to the control plane.
	// If no heartbeat is received within 3x the poll interval (default 90s),
	// the agent transitions to UNREACHABLE status.
	//
	// Scope: `agents:heartbeat` | Token types: `agt`
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewAgentAPIClient constructs a client for the admiral.api.agent.v1.AgentAPI service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAgentAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AgentAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	agentAPIMethods := v1.File_agent_v1_agent_proto.Services().ByName("AgentAPI").Methods()
	return &agentAPIClient{
		registerAgent: connect.NewClient[v1.RegisterAgentRequest, v1.RegisterAgentResponse](
			httpClient,
			baseURL+AgentAPIRegisterAgentProcedure,
			connect.WithSchema(agentAPIMethods.ByName("RegisterAgent")),
			connect.WithClientOptions(opts...),
		),
		getAgent: connect.NewClient[v1.GetAgentRequest, v1.GetAgentResponse](
			httpClient,
			baseURL+AgentAPIGetAgentProcedure,
			connect.WithSchema(agentAPIMethods.ByName("GetAgent")),
			connect.WithClientOptions(opts...),
		),
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+AgentAPIListAgentsProcedure,
			connect.WithSchema(agentAPIMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[v1.HeartbeatRequest, v1.HeartbeatResponse](
			httpClient,
			baseURL+AgentAPIHeartbeatProcedure,
			connect.WithSchema(agentAPIMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
	}
}

// agentAPIClient implements AgentAPIClient.
type agentAPIClient struct {
	registerAgent *connect.Client[v1.RegisterAgentRequest, v1.RegisterAgentResponse]
	getAgent      *connect.Client[v1.GetAgentRequest, v1.GetAgentResponse]
	listAgents    *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	heartbeat     *connect.Client[v1.HeartbeatRequest, v1.HeartbeatResponse]
}

// RegisterAgent calls admiral.api.agent.v1.AgentAPI.RegisterAgent.
func (c *agentAPIClient) RegisterAgent(ctx context.Context, req *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error) {
	return c.registerAgent.CallUnary(ctx, req)
}

// GetAgent calls admiral.api.agent.v1.AgentAPI.GetAgent.
func (c *agentAPIClient) GetAgent(ctx context.Context, req *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return c.getAgent.CallUnary(ctx, req)
}

// ListAgents calls admiral.api.agent.v1.AgentAPI.ListAgents.
func (c *agentAPIClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// Heartbeat calls admiral.api.agent.v1.AgentAPI.Heartbeat.
func (c *agentAPIClient) Heartbeat(ctx context.Context, req *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// AgentAPIHandler is an implementation of the admiral.api.agent.v1.AgentAPI service.
type AgentAPIHandler interface {
	// RegisterAgent registers a new agent, binding it to its parent resource
	// (Cluster or Runner). The binding is derived from the AGT used to
	// authenticate — the request does not specify which resource to bind to.
	//
	// For Kubernetes agents, the request must include `cluster_uid` (the
	// kube-system namespace UID). This value is written to the Cluster record
	// using a first-write-wins strategy. Subsequent registrations with a
	// different UID return 409 Conflict.
	//
	// Registration is idempotent: if the agent restarts and calls RegisterAgent
	// with the same AGT and matching metadata, the existing agent record is
	// returned and its status is set to ONLINE.
	//
	// Scope: `agents:write` | Token types: `agt`
	RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error)
	// GetAgent retrieves an agent by ID, including its current connectivity
	// status and resource binding.
	//
	// Scope: `agents:read`
	GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error)
	// ListAgents returns a paginated list of agents within the caller's tenant.
	// Use the filter parameter to scope results by resource binding
	// (e.g., `cluster_id = "uuid"` or `runner_id = "uuid"`).
	//
	// Scope: `agents:read`
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// Heartbeat sends a liveness signal from the agent to the control plane.
	// If no heartbeat is received within 3x the poll interval (default 90s),
	// the agent transitions to UNREACHABLE status.
	//
	// Scope: `agents:heartbeat` | Token types: `agt`
	Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error)
}

// NewAgentAPIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAgentAPIHandler(svc AgentAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	agentAPIMethods := v1.File_agent_v1_agent_proto.Services().ByName("AgentAPI").Methods()
	agentAPIRegisterAgentHandler := connect.NewUnaryHandler(
		AgentAPIRegisterAgentProcedure,
		svc.RegisterAgent,
		connect.WithSchema(agentAPIMethods.ByName("RegisterAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentAPIGetAgentHandler := connect.NewUnaryHandler(
		AgentAPIGetAgentProcedure,
		svc.GetAgent,
		connect.WithSchema(agentAPIMethods.ByName("GetAgent")),
		connect.WithHandlerOptions(opts...),
	)
	agentAPIListAgentsHandler := connect.NewUnaryHandler(
		AgentAPIListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(agentAPIMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	agentAPIHeartbeatHandler := connect.NewUnaryHandler(
		AgentAPIHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(agentAPIMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	return "/admiral.api.agent.v1.AgentAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AgentAPIRegisterAgentProcedure:
			agentAPIRegisterAgentHandler.ServeHTTP(w, r)
		case AgentAPIGetAgentProcedure:
			agentAPIGetAgentHandler.ServeHTTP(w, r)
		case AgentAPIListAgentsProcedure:
			agentAPIListAgentsHandler.ServeHTTP(w, r)
		case AgentAPIHeartbeatProcedure:
			agentAPIHeartbeatHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAgentAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedAgentAPIHandler struct{}

func (UnimplementedAgentAPIHandler) RegisterAgent(context.Context, *connect.Request[v1.RegisterAgentRequest]) (*connect.Response[v1.RegisterAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.agent.v1.AgentAPI.RegisterAgent is not implemented"))
}

func (UnimplementedAgentAPIHandler) GetAgent(context.Context, *connect.Request[v1.GetAgentRequest]) (*connect.Response[v1.GetAgentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.agent.v1.AgentAPI.GetAgent is not implemented"))
}

func (UnimplementedAgentAPIHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.agent.v1.AgentAPI.ListAgents is not implemented"))
}

func (UnimplementedAgentAPIHandler) Heartbeat(context.Context, *connect.Request[v1.HeartbeatRequest]) (*connect.Response[v1.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("admiral.api.agent.v1.AgentAPI.Heartbeat is not implemented"))
}
