// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: authz/v1/annotations.proto

package authzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TokenType identifies the category of an access token issued by Admiral's token system.
// IDP-issued JWTs (OAuth2/OIDC sessions) are NOT represented here — they are
// resolved by separate middleware and can be referenced as "session" in
// AuthRule.allowed_token_types when needed.
type TokenType int32

const (
	TokenType_TOKEN_TYPE_UNSPECIFIED TokenType = 0
	TokenType_PERSONAL_ACCESS_TOKEN  TokenType = 1
	TokenType_SERVICE_ACCOUNT_TOKEN  TokenType = 2
	TokenType_AGENT_TOKEN            TokenType = 3
)

// Enum value maps for TokenType.
var (
	TokenType_name = map[int32]string{
		0: "TOKEN_TYPE_UNSPECIFIED",
		1: "PERSONAL_ACCESS_TOKEN",
		2: "SERVICE_ACCOUNT_TOKEN",
		3: "AGENT_TOKEN",
	}
	TokenType_value = map[string]int32{
		"TOKEN_TYPE_UNSPECIFIED": 0,
		"PERSONAL_ACCESS_TOKEN":  1,
		"SERVICE_ACCOUNT_TOKEN":  2,
		"AGENT_TOKEN":            3,
	}
)

func (x TokenType) Enum() *TokenType {
	p := new(TokenType)
	*p = x
	return p
}

func (x TokenType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenType) Descriptor() protoreflect.EnumDescriptor {
	return file_authz_v1_annotations_proto_enumTypes[0].Descriptor()
}

func (TokenType) Type() protoreflect.EnumType {
	return &file_authz_v1_annotations_proto_enumTypes[0]
}

func (x TokenType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenType.Descriptor instead.
func (TokenType) EnumDescriptor() ([]byte, []int) {
	return file_authz_v1_annotations_proto_rawDescGZIP(), []int{0}
}

// AuthRule defines the authorization requirements for an RPC method.
// Applied as a custom method option and enforced at runtime by a Connect interceptor.
//
// The presence of the option means the RPC requires authentication.
// An empty scope means any authenticated request is sufficient.
type AuthRule struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The scope required to call this RPC (e.g., "clusters:read").
	// Empty string means any valid token is sufficient — no specific scope required.
	Scope string `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// Restrict to specific token types ("pat", "sat", "agt", "session").
	// Empty means all token types are allowed.
	AllowedTokenTypes []string `protobuf:"bytes,2,rep,name=allowed_token_types,json=allowedTokenTypes,proto3" json:"allowed_token_types,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuthRule) Reset() {
	*x = AuthRule{}
	mi := &file_authz_v1_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRule) ProtoMessage() {}

func (x *AuthRule) ProtoReflect() protoreflect.Message {
	mi := &file_authz_v1_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRule.ProtoReflect.Descriptor instead.
func (*AuthRule) Descriptor() ([]byte, []int) {
	return file_authz_v1_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRule) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *AuthRule) GetAllowedTokenTypes() []string {
	if x != nil {
		return x.AllowedTokenTypes
	}
	return nil
}

var file_authz_v1_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*AuthRule)(nil),
		Field:         50000,
		Name:          "admiral.api.authz.v1.rule",
		Tag:           "bytes,50000,opt,name=rule",
		Filename:      "authz/v1/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional admiral.api.authz.v1.AuthRule rule = 50000;
	E_Rule = &file_authz_v1_annotations_proto_extTypes[0]
)

var File_authz_v1_annotations_proto protoreflect.FileDescriptor

const file_authz_v1_annotations_proto_rawDesc = "" +
	"\n" +
	"\x1aauthz/v1/annotations.proto\x12\x14admiral.api.authz.v1\x1a google/protobuf/descriptor.proto\"P\n" +
	"\bAuthRule\x12\x14\n" +
	"\x05scope\x18\x01 \x01(\tR\x05scope\x12.\n" +
	"\x13allowed_token_types\x18\x02 \x03(\tR\x11allowedTokenTypes*n\n" +
	"\tTokenType\x12\x1a\n" +
	"\x16TOKEN_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PERSONAL_ACCESS_TOKEN\x10\x01\x12\x19\n" +
	"\x15SERVICE_ACCOUNT_TOKEN\x10\x02\x12\x0f\n" +
	"\vAGENT_TOKEN\x10\x03:W\n" +
	"\x04rule\x12\x1e.google.protobuf.MethodOptions\x18І\x03 \x01(\v2\x1e.admiral.api.authz.v1.AuthRuleR\x04rule\x88\x01\x01B\xc9\x01\n" +
	"\x18com.admiral.api.authz.v1B\x10AnnotationsProtoP\x01Z(go.admiral.io/sdk/proto/authz/v1;authzv1\xa2\x02\x03AAA\xaa\x02\x14Admiral.Api.Authz.V1\xca\x02\x14Admiral\\Api\\Authz\\V1\xe2\x02 Admiral\\Api\\Authz\\V1\\GPBMetadata\xea\x02\x17Admiral::Api::Authz::V1b\x06proto3"

var (
	file_authz_v1_annotations_proto_rawDescOnce sync.Once
	file_authz_v1_annotations_proto_rawDescData []byte
)

func file_authz_v1_annotations_proto_rawDescGZIP() []byte {
	file_authz_v1_annotations_proto_rawDescOnce.Do(func() {
		file_authz_v1_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authz_v1_annotations_proto_rawDesc), len(file_authz_v1_annotations_proto_rawDesc)))
	})
	return file_authz_v1_annotations_proto_rawDescData
}

var file_authz_v1_annotations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_authz_v1_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authz_v1_annotations_proto_goTypes = []any{
	(TokenType)(0),                     // 0: admiral.api.authz.v1.TokenType
	(*AuthRule)(nil),                   // 1: admiral.api.authz.v1.AuthRule
	(*descriptorpb.MethodOptions)(nil), // 2: google.protobuf.MethodOptions
}
var file_authz_v1_annotations_proto_depIdxs = []int32{
	2, // 0: admiral.api.authz.v1.rule:extendee -> google.protobuf.MethodOptions
	1, // 1: admiral.api.authz.v1.rule:type_name -> admiral.api.authz.v1.AuthRule
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authz_v1_annotations_proto_init() }
func file_authz_v1_annotations_proto_init() {
	if File_authz_v1_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authz_v1_annotations_proto_rawDesc), len(file_authz_v1_annotations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_authz_v1_annotations_proto_goTypes,
		DependencyIndexes: file_authz_v1_annotations_proto_depIdxs,
		EnumInfos:         file_authz_v1_annotations_proto_enumTypes,
		MessageInfos:      file_authz_v1_annotations_proto_msgTypes,
		ExtensionInfos:    file_authz_v1_annotations_proto_extTypes,
	}.Build()
	File_authz_v1_annotations_proto = out.File
	file_authz_v1_annotations_proto_goTypes = nil
	file_authz_v1_annotations_proto_depIdxs = nil
}
