// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: runner/v1/runner.proto

package runnerv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Runner with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Runner) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Runner with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in RunnerMultiError, or nil if none found.
func (m *Runner) ValidateAll() error {
	return m.validate(true)
}

func (m *Runner) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for TenantId

	// no validation rules for DisplayName

	// no validation rules for Kind

	// no validation rules for Labels

	if all {
		switch v := interface{}(m.GetCreatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunnerValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunnerValidationError{
					field:  "CreatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetCreatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunnerValidationError{
				field:  "CreatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdatedAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RunnerValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RunnerValidationError{
					field:  "UpdatedAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdatedAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RunnerValidationError{
				field:  "UpdatedAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RunnerMultiError(errors)
	}

	return nil
}

// RunnerMultiError is an error wrapping multiple validation errors returned by
// Runner.ValidateAll() if the designated constraints aren't met.
type RunnerMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RunnerMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RunnerMultiError) AllErrors() []error { return m }

// RunnerValidationError is the validation error returned by Runner.Validate if
// the designated constraints aren't met.
type RunnerValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RunnerValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RunnerValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RunnerValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RunnerValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RunnerValidationError) ErrorName() string { return "RunnerValidationError" }

// Error satisfies the builtin error interface
func (e RunnerValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRunner.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RunnerValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RunnerValidationError{}

// Validate checks the field values on CreateRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRunnerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRunnerRequestMultiError, or nil if none found.
func (m *CreateRunnerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRunnerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for DisplayName

	// no validation rules for Kind

	// no validation rules for Labels

	if len(errors) > 0 {
		return CreateRunnerRequestMultiError(errors)
	}

	return nil
}

// CreateRunnerRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRunnerRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRunnerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRunnerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRunnerRequestMultiError) AllErrors() []error { return m }

// CreateRunnerRequestValidationError is the validation error returned by
// CreateRunnerRequest.Validate if the designated constraints aren't met.
type CreateRunnerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRunnerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRunnerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRunnerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRunnerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRunnerRequestValidationError) ErrorName() string {
	return "CreateRunnerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRunnerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRunnerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRunnerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRunnerRequestValidationError{}

// Validate checks the field values on CreateRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRunnerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRunnerResponseMultiError, or nil if none found.
func (m *CreateRunnerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRunnerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRunner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRunner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRunnerResponseValidationError{
				field:  "Runner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PlainTextToken

	if len(errors) > 0 {
		return CreateRunnerResponseMultiError(errors)
	}

	return nil
}

// CreateRunnerResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRunnerResponse.ValidateAll() if the designated
// constraints aren't met.
type CreateRunnerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRunnerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRunnerResponseMultiError) AllErrors() []error { return m }

// CreateRunnerResponseValidationError is the validation error returned by
// CreateRunnerResponse.Validate if the designated constraints aren't met.
type CreateRunnerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRunnerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRunnerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRunnerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRunnerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRunnerResponseValidationError) ErrorName() string {
	return "CreateRunnerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRunnerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRunnerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRunnerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRunnerResponseValidationError{}

// Validate checks the field values on GetRunnerRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRunnerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRunnerRequestMultiError, or nil if none found.
func (m *GetRunnerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRunnerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	if len(errors) > 0 {
		return GetRunnerRequestMultiError(errors)
	}

	return nil
}

// GetRunnerRequestMultiError is an error wrapping multiple validation errors
// returned by GetRunnerRequest.ValidateAll() if the designated constraints
// aren't met.
type GetRunnerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRunnerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRunnerRequestMultiError) AllErrors() []error { return m }

// GetRunnerRequestValidationError is the validation error returned by
// GetRunnerRequest.Validate if the designated constraints aren't met.
type GetRunnerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRunnerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRunnerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRunnerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRunnerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRunnerRequestValidationError) ErrorName() string { return "GetRunnerRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetRunnerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRunnerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRunnerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRunnerRequestValidationError{}

// Validate checks the field values on GetRunnerResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetRunnerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRunnerResponseMultiError, or nil if none found.
func (m *GetRunnerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRunnerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRunner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRunner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRunnerResponseValidationError{
				field:  "Runner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRunnerResponseMultiError(errors)
	}

	return nil
}

// GetRunnerResponseMultiError is an error wrapping multiple validation errors
// returned by GetRunnerResponse.ValidateAll() if the designated constraints
// aren't met.
type GetRunnerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRunnerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRunnerResponseMultiError) AllErrors() []error { return m }

// GetRunnerResponseValidationError is the validation error returned by
// GetRunnerResponse.Validate if the designated constraints aren't met.
type GetRunnerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRunnerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRunnerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRunnerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRunnerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRunnerResponseValidationError) ErrorName() string {
	return "GetRunnerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRunnerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRunnerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRunnerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRunnerResponseValidationError{}

// Validate checks the field values on ListRunnersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRunnersRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunnersRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunnersRequestMultiError, or nil if none found.
func (m *ListRunnersRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunnersRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for Filter

	if len(errors) > 0 {
		return ListRunnersRequestMultiError(errors)
	}

	return nil
}

// ListRunnersRequestMultiError is an error wrapping multiple validation errors
// returned by ListRunnersRequest.ValidateAll() if the designated constraints
// aren't met.
type ListRunnersRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunnersRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunnersRequestMultiError) AllErrors() []error { return m }

// ListRunnersRequestValidationError is the validation error returned by
// ListRunnersRequest.Validate if the designated constraints aren't met.
type ListRunnersRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunnersRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunnersRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunnersRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunnersRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunnersRequestValidationError) ErrorName() string {
	return "ListRunnersRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRunnersRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunnersRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunnersRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunnersRequestValidationError{}

// Validate checks the field values on ListRunnersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRunnersResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunnersResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunnersResponseMultiError, or nil if none found.
func (m *ListRunnersResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunnersResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetRunners() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRunnersResponseValidationError{
						field:  fmt.Sprintf("Runners[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRunnersResponseValidationError{
						field:  fmt.Sprintf("Runners[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRunnersResponseValidationError{
					field:  fmt.Sprintf("Runners[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListRunnersResponseMultiError(errors)
	}

	return nil
}

// ListRunnersResponseMultiError is an error wrapping multiple validation
// errors returned by ListRunnersResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRunnersResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunnersResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunnersResponseMultiError) AllErrors() []error { return m }

// ListRunnersResponseValidationError is the validation error returned by
// ListRunnersResponse.Validate if the designated constraints aren't met.
type ListRunnersResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunnersResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunnersResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunnersResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunnersResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunnersResponseValidationError) ErrorName() string {
	return "ListRunnersResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRunnersResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunnersResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunnersResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunnersResponseValidationError{}

// Validate checks the field values on UpdateRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRunnerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRunnerRequestMultiError, or nil if none found.
func (m *UpdateRunnerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRunnerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRunner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRunnerRequestValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRunnerRequestValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRunner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRunnerRequestValidationError{
				field:  "Runner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetUpdateMask()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRunnerRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRunnerRequestValidationError{
					field:  "UpdateMask",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetUpdateMask()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRunnerRequestValidationError{
				field:  "UpdateMask",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRunnerRequestMultiError(errors)
	}

	return nil
}

// UpdateRunnerRequestMultiError is an error wrapping multiple validation
// errors returned by UpdateRunnerRequest.ValidateAll() if the designated
// constraints aren't met.
type UpdateRunnerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRunnerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRunnerRequestMultiError) AllErrors() []error { return m }

// UpdateRunnerRequestValidationError is the validation error returned by
// UpdateRunnerRequest.Validate if the designated constraints aren't met.
type UpdateRunnerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRunnerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRunnerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRunnerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRunnerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRunnerRequestValidationError) ErrorName() string {
	return "UpdateRunnerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRunnerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRunnerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRunnerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRunnerRequestValidationError{}

// Validate checks the field values on UpdateRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UpdateRunnerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UpdateRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UpdateRunnerResponseMultiError, or nil if none found.
func (m *UpdateRunnerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UpdateRunnerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetRunner()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, UpdateRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, UpdateRunnerResponseValidationError{
					field:  "Runner",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetRunner()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return UpdateRunnerResponseValidationError{
				field:  "Runner",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return UpdateRunnerResponseMultiError(errors)
	}

	return nil
}

// UpdateRunnerResponseMultiError is an error wrapping multiple validation
// errors returned by UpdateRunnerResponse.ValidateAll() if the designated
// constraints aren't met.
type UpdateRunnerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UpdateRunnerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UpdateRunnerResponseMultiError) AllErrors() []error { return m }

// UpdateRunnerResponseValidationError is the validation error returned by
// UpdateRunnerResponse.Validate if the designated constraints aren't met.
type UpdateRunnerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UpdateRunnerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UpdateRunnerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UpdateRunnerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UpdateRunnerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UpdateRunnerResponseValidationError) ErrorName() string {
	return "UpdateRunnerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UpdateRunnerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUpdateRunnerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UpdateRunnerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UpdateRunnerResponseValidationError{}

// Validate checks the field values on DeleteRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRunnerRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRunnerRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRunnerRequestMultiError, or nil if none found.
func (m *DeleteRunnerRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRunnerRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	if len(errors) > 0 {
		return DeleteRunnerRequestMultiError(errors)
	}

	return nil
}

// DeleteRunnerRequestMultiError is an error wrapping multiple validation
// errors returned by DeleteRunnerRequest.ValidateAll() if the designated
// constraints aren't met.
type DeleteRunnerRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRunnerRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRunnerRequestMultiError) AllErrors() []error { return m }

// DeleteRunnerRequestValidationError is the validation error returned by
// DeleteRunnerRequest.Validate if the designated constraints aren't met.
type DeleteRunnerRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRunnerRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRunnerRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRunnerRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRunnerRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRunnerRequestValidationError) ErrorName() string {
	return "DeleteRunnerRequestValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRunnerRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRunnerRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRunnerRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRunnerRequestValidationError{}

// Validate checks the field values on DeleteRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *DeleteRunnerResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on DeleteRunnerResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// DeleteRunnerResponseMultiError, or nil if none found.
func (m *DeleteRunnerResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *DeleteRunnerResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return DeleteRunnerResponseMultiError(errors)
	}

	return nil
}

// DeleteRunnerResponseMultiError is an error wrapping multiple validation
// errors returned by DeleteRunnerResponse.ValidateAll() if the designated
// constraints aren't met.
type DeleteRunnerResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m DeleteRunnerResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m DeleteRunnerResponseMultiError) AllErrors() []error { return m }

// DeleteRunnerResponseValidationError is the validation error returned by
// DeleteRunnerResponse.Validate if the designated constraints aren't met.
type DeleteRunnerResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e DeleteRunnerResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e DeleteRunnerResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e DeleteRunnerResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e DeleteRunnerResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e DeleteRunnerResponseValidationError) ErrorName() string {
	return "DeleteRunnerResponseValidationError"
}

// Error satisfies the builtin error interface
func (e DeleteRunnerResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sDeleteRunnerResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = DeleteRunnerResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = DeleteRunnerResponseValidationError{}

// Validate checks the field values on CreateRunnerTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRunnerTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRunnerTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRunnerTokenRequestMultiError, or nil if none found.
func (m *CreateRunnerTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRunnerTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	// no validation rules for DisplayName

	if all {
		switch v := interface{}(m.GetExpiresAt()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRunnerTokenRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRunnerTokenRequestValidationError{
					field:  "ExpiresAt",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetExpiresAt()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRunnerTokenRequestValidationError{
				field:  "ExpiresAt",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return CreateRunnerTokenRequestMultiError(errors)
	}

	return nil
}

// CreateRunnerTokenRequestMultiError is an error wrapping multiple validation
// errors returned by CreateRunnerTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type CreateRunnerTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRunnerTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRunnerTokenRequestMultiError) AllErrors() []error { return m }

// CreateRunnerTokenRequestValidationError is the validation error returned by
// CreateRunnerTokenRequest.Validate if the designated constraints aren't met.
type CreateRunnerTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRunnerTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRunnerTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRunnerTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRunnerTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRunnerTokenRequestValidationError) ErrorName() string {
	return "CreateRunnerTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRunnerTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRunnerTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRunnerTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRunnerTokenRequestValidationError{}

// Validate checks the field values on CreateRunnerTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *CreateRunnerTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on CreateRunnerTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// CreateRunnerTokenResponseMultiError, or nil if none found.
func (m *CreateRunnerTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *CreateRunnerTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccessToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, CreateRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, CreateRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccessToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return CreateRunnerTokenResponseValidationError{
				field:  "AccessToken",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	// no validation rules for PlainTextToken

	if len(errors) > 0 {
		return CreateRunnerTokenResponseMultiError(errors)
	}

	return nil
}

// CreateRunnerTokenResponseMultiError is an error wrapping multiple validation
// errors returned by CreateRunnerTokenResponse.ValidateAll() if the
// designated constraints aren't met.
type CreateRunnerTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m CreateRunnerTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m CreateRunnerTokenResponseMultiError) AllErrors() []error { return m }

// CreateRunnerTokenResponseValidationError is the validation error returned by
// CreateRunnerTokenResponse.Validate if the designated constraints aren't met.
type CreateRunnerTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e CreateRunnerTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e CreateRunnerTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e CreateRunnerTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e CreateRunnerTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e CreateRunnerTokenResponseValidationError) ErrorName() string {
	return "CreateRunnerTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e CreateRunnerTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sCreateRunnerTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = CreateRunnerTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = CreateRunnerTokenResponseValidationError{}

// Validate checks the field values on ListRunnerTokensRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRunnerTokensRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunnerTokensRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunnerTokensRequestMultiError, or nil if none found.
func (m *ListRunnerTokensRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunnerTokensRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	// no validation rules for PageSize

	// no validation rules for PageToken

	// no validation rules for Filter

	if len(errors) > 0 {
		return ListRunnerTokensRequestMultiError(errors)
	}

	return nil
}

// ListRunnerTokensRequestMultiError is an error wrapping multiple validation
// errors returned by ListRunnerTokensRequest.ValidateAll() if the designated
// constraints aren't met.
type ListRunnerTokensRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunnerTokensRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunnerTokensRequestMultiError) AllErrors() []error { return m }

// ListRunnerTokensRequestValidationError is the validation error returned by
// ListRunnerTokensRequest.Validate if the designated constraints aren't met.
type ListRunnerTokensRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunnerTokensRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunnerTokensRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunnerTokensRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunnerTokensRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunnerTokensRequestValidationError) ErrorName() string {
	return "ListRunnerTokensRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListRunnerTokensRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunnerTokensRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunnerTokensRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunnerTokensRequestValidationError{}

// Validate checks the field values on ListRunnerTokensResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListRunnerTokensResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListRunnerTokensResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListRunnerTokensResponseMultiError, or nil if none found.
func (m *ListRunnerTokensResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListRunnerTokensResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetAccessTokens() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ListRunnerTokensResponseValidationError{
						field:  fmt.Sprintf("AccessTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ListRunnerTokensResponseValidationError{
						field:  fmt.Sprintf("AccessTokens[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ListRunnerTokensResponseValidationError{
					field:  fmt.Sprintf("AccessTokens[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	// no validation rules for NextPageToken

	if len(errors) > 0 {
		return ListRunnerTokensResponseMultiError(errors)
	}

	return nil
}

// ListRunnerTokensResponseMultiError is an error wrapping multiple validation
// errors returned by ListRunnerTokensResponse.ValidateAll() if the designated
// constraints aren't met.
type ListRunnerTokensResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListRunnerTokensResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListRunnerTokensResponseMultiError) AllErrors() []error { return m }

// ListRunnerTokensResponseValidationError is the validation error returned by
// ListRunnerTokensResponse.Validate if the designated constraints aren't met.
type ListRunnerTokensResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListRunnerTokensResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListRunnerTokensResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListRunnerTokensResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListRunnerTokensResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListRunnerTokensResponseValidationError) ErrorName() string {
	return "ListRunnerTokensResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListRunnerTokensResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListRunnerTokensResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListRunnerTokensResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListRunnerTokensResponseValidationError{}

// Validate checks the field values on GetRunnerTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRunnerTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRunnerTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRunnerTokenRequestMultiError, or nil if none found.
func (m *GetRunnerTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRunnerTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	// no validation rules for TokenId

	if len(errors) > 0 {
		return GetRunnerTokenRequestMultiError(errors)
	}

	return nil
}

// GetRunnerTokenRequestMultiError is an error wrapping multiple validation
// errors returned by GetRunnerTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type GetRunnerTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRunnerTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRunnerTokenRequestMultiError) AllErrors() []error { return m }

// GetRunnerTokenRequestValidationError is the validation error returned by
// GetRunnerTokenRequest.Validate if the designated constraints aren't met.
type GetRunnerTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRunnerTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRunnerTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRunnerTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRunnerTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRunnerTokenRequestValidationError) ErrorName() string {
	return "GetRunnerTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetRunnerTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRunnerTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRunnerTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRunnerTokenRequestValidationError{}

// Validate checks the field values on GetRunnerTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetRunnerTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetRunnerTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetRunnerTokenResponseMultiError, or nil if none found.
func (m *GetRunnerTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetRunnerTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccessToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, GetRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, GetRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccessToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return GetRunnerTokenResponseValidationError{
				field:  "AccessToken",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return GetRunnerTokenResponseMultiError(errors)
	}

	return nil
}

// GetRunnerTokenResponseMultiError is an error wrapping multiple validation
// errors returned by GetRunnerTokenResponse.ValidateAll() if the designated
// constraints aren't met.
type GetRunnerTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetRunnerTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetRunnerTokenResponseMultiError) AllErrors() []error { return m }

// GetRunnerTokenResponseValidationError is the validation error returned by
// GetRunnerTokenResponse.Validate if the designated constraints aren't met.
type GetRunnerTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetRunnerTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetRunnerTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetRunnerTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetRunnerTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetRunnerTokenResponseValidationError) ErrorName() string {
	return "GetRunnerTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetRunnerTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetRunnerTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetRunnerTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetRunnerTokenResponseValidationError{}

// Validate checks the field values on RevokeRunnerTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeRunnerTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeRunnerTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevokeRunnerTokenRequestMultiError, or nil if none found.
func (m *RevokeRunnerTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeRunnerTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RunnerId

	// no validation rules for TokenId

	if len(errors) > 0 {
		return RevokeRunnerTokenRequestMultiError(errors)
	}

	return nil
}

// RevokeRunnerTokenRequestMultiError is an error wrapping multiple validation
// errors returned by RevokeRunnerTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type RevokeRunnerTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeRunnerTokenRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeRunnerTokenRequestMultiError) AllErrors() []error { return m }

// RevokeRunnerTokenRequestValidationError is the validation error returned by
// RevokeRunnerTokenRequest.Validate if the designated constraints aren't met.
type RevokeRunnerTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeRunnerTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeRunnerTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeRunnerTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeRunnerTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeRunnerTokenRequestValidationError) ErrorName() string {
	return "RevokeRunnerTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeRunnerTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeRunnerTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeRunnerTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeRunnerTokenRequestValidationError{}

// Validate checks the field values on RevokeRunnerTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RevokeRunnerTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RevokeRunnerTokenResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RevokeRunnerTokenResponseMultiError, or nil if none found.
func (m *RevokeRunnerTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *RevokeRunnerTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetAccessToken()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, RevokeRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, RevokeRunnerTokenResponseValidationError{
					field:  "AccessToken",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetAccessToken()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return RevokeRunnerTokenResponseValidationError{
				field:  "AccessToken",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return RevokeRunnerTokenResponseMultiError(errors)
	}

	return nil
}

// RevokeRunnerTokenResponseMultiError is an error wrapping multiple validation
// errors returned by RevokeRunnerTokenResponse.ValidateAll() if the
// designated constraints aren't met.
type RevokeRunnerTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RevokeRunnerTokenResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RevokeRunnerTokenResponseMultiError) AllErrors() []error { return m }

// RevokeRunnerTokenResponseValidationError is the validation error returned by
// RevokeRunnerTokenResponse.Validate if the designated constraints aren't met.
type RevokeRunnerTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RevokeRunnerTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RevokeRunnerTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RevokeRunnerTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RevokeRunnerTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RevokeRunnerTokenResponseValidationError) ErrorName() string {
	return "RevokeRunnerTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e RevokeRunnerTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRevokeRunnerTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RevokeRunnerTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RevokeRunnerTokenResponseValidationError{}
